### ISSUE TITLE
Error in funtion 'setmetatable'

### ISSUE THREAD

**Issue by padpad17** [copycat-killer/awesome-copycats#101]
Hi,

i just fresh installed awesome and pulled your ( great ) themes. However i getting the following error with every rc.lua.theme file. I pulled lain from git and installed all requirements but i still get those errors.

error while running function
stack traceback:
	[C]: in function 'setmetatable'
	/home/padpad/.config/awesome/lain/widgets/bat.lua:162: in main chunk
	[C]: in function 'require'
	/home/padpad/.config/awesome/lain/helpers.lua:29: in function 'lain.helpers.wrequire'
	/home/padpad/.config/awesome/rc.lua:193: in main chunk
error: /home/padpad/.config/awesome/lain/widgets/bat.lua:162: bad argument #1 to 'setmetatable' (table expected, got nil)

**Comment by copycat-killer** [comment]
Are you sure you've not incapped in [this one](https://github.com/copycat-killer/lain/pull/147)?

Grab latest Lain:

```shell
cd $HOME/.config/awesome/lain; git pull
```

then restart Awesome.

**Comment by padpad17** [comment]
Hi,

thanks for the fast reply. git pull says i am already up-to-date!

**Comment by padpad17** [comment]
Hi again

i pulled patch-2 branch from stwa/lain fork which resolved this issue. But i still get an error from net.lua though:

```bash
/home/padpad/.config/awesome/lain/widgets/net.lua:75 attempt to perform arithemtic an a nil value ( field 'last_t')
```

**Comment by copycat-killer** [comment]
You are not in the master branch, plus that fork is not updated.

Do a `git clone` from scratch, or checkout to master and `git pull` again.

**Comment by padpad17** [comment]
Yes, i already wiped the lain/ directory and installed lain-git via the arch AUR repository but then i have the bat.lua issue again. The bat.lua file in master branch still contains 

```lua
return setmetatable(bat, { __call = function(_, ...) return worker(...) end })
```

**Comment by copycat-killer** [comment]
You're right.

`git clone` from here latest lain commt (0b80b45). I'll update the AUR pkgbuild later.

It should be ok now.

**Comment by padpad17** [comment]
Thank you very much for your help and for this great themes!

**Comment by copycat-killer** [comment]
Thank you for using them. :dancers:
