### ISSUE TITLE
Change Layouts ?

### ISSUE THREAD

**Issue by HawN** [copycat-killer/awesome-copycats#102]
Hello, for change Layouts, i need modify only those lines ? Or something else ? 

local layouts = {
    awful.layout.suit.floating,
    awful.layout.suit.tile,
    awful.layout.suit.tile.left,
    awful.layout.suit.tile.bottom,
    awful.layout.suit.tile.top,
    awful.layout.suit.fair,
    awful.layout.suit.fair.horizontal,
    awful.layout.suit.spiral,
    awful.layout.suit.spiral.dwindle,
    awful.layout.suit.max,
}

For exemple if i want add layout : lain.layout.uselesstile  on the multicolor lua theme, i only add : lain.layout.uselesstile ? Or something else ?

Because i'm lost with :  layout = { layouts[1], layouts[3], layouts[4], layouts[1], layouts[7], layouts[1] }

Thank's

**Comment by copycat-killer** [comment]
Yes, you just have to add it to `layouts`. Read [here](http://awesome.naquadah.org/wiki/My_first_awesome#Personalize_your_tags).

I'm sure that everything you need is covered in the [official wiki](http://awesome.naquadah.org/wiki/Main_Page).

If you want further informations on the basics, please search there.
