### ISSUE TITLE
Change size of icons applets on top bar

### ISSUE THREAD

**Issue by HawN** [copycat-killer/awesome-copycats#103]
Hello, how can i change the size of icons apps on top bar ? 

Thank's

**Comment by copycat-killer** [comment]
Use [`wibox.widget.imagebox:fit(width, height)`](https://awesome.naquadah.org/doc/api/modules/wibox.widget.imagebox.html#fit).

Example with multicolor's textclock:
```lua
clockicon = wibox.widget.imagebox(beautiful.widget_clock)
clockicon:fit(18, 18)
```

See also [`set_resize`](https://awesome.naquadah.org/doc/api/modules/wibox.widget.imagebox.html#set_resize).

This is a priority to-do list you should follow when you have a generic question:

1. check the [wiki](http://awesome.naquadah.org/wiki/Main_Page) first;
2. check the [API](https://awesome.naquadah.org/doc/api/modules/wibox.widget.imagebox.html);
3. Google it;
4. ask the [community](http://awesome.naquadah.org/community/).
