### ISSUE TITLE
Blackburn

### ISSUE THREAD

**Issue by christ0f** [copycat-killer/awesome-copycats#105]
Hi, new to the site and linux in general so if this section is for real issues only I apologise, I have managed to get awesome running on ubuntu on my chromebook after many mistakes but now I cant find the icons on the top left corner of blackburn theme for the life of me, not sure if I have just over looked them but help would be appreciated
(I changed the tags to cmd and www because I couldn't get the icons, I am aware that they are different in the blackburn rc.lua I can change them back when needed)
Thanks.

![screenshot](https://cloud.githubusercontent.com/assets/13962361/11018263/b5a93270-85b9-11e5-9baa-fa9dcdfba0c4.png)

**Comment by copycat-killer** [comment]
Not icons, it's a font. Read [here](https://github.com/copycat-killer/awesome-copycats#notes).

[Download](https://raw.githubusercontent.com/copycat-killer/dots/master/.fonts/Icons.bdf) and install it [manually](https://wiki.ubuntu.com/Fonts#Manually). Also, be sure to have [bitmaps enabled](https://wiki.ubuntu.com/Fonts#Enabling_Bitmapped_Fonts).
