### ISSUE TITLE
Duplicate dropdown clients

### ISSUE THREAD

**Issue by jjeziorny** [copycat-killer/awesome-copycats#108]
Everytime awesome is restarted (manyally or when pluging/unpluging a new monitor) the existing dropdown client window (xfce4-termianl) becomes a normal client and when my keybindings to dropdown are pressent again a new terminal is spawn leaving the old one as a normal client. So basically I endup with duplicate clients, and the old one has all my open tabs which annoyingly I have to close and re-open on the new dropdown client.

This happens with any app I use with scratchdrop, I have another keybinding for thunar and the same happens.

**Comment by copycat-killer** [comment]
I know, this is a limit of `scratchdrop`. It's a very simple module, after all.

This third party software, if you read its entry in the Awesome wiki you can see there's [another solution](http://awesome.naquadah.org/wiki/Drop-down_terminal#Another_solution) which solves your problem.

I don't rely too much on `scratchdrop`, but in case there'll be a considerable request from users, I'll consider switching to `quake`.

**Comment by copycat-killer** [comment]
I decided to switch to `quake`, I also made it behave like `scratchdrop` so we have best of both now.
