### ISSUE TITLE
an error was happened 

### ISSUE THREAD

**Issue by ascrutae** [copycat-killer/awesome-copycats#110]
errormessage :./lain/widgets/alsabar.lua:130 bad argument #1 to 'match' (string expected got nil) 
my version:
lua version:5.3.2
awesome:3.5.9

**Comment by andering** [comment]
1. do you use default mixer - amixer ?
2. if you do than what you get if you put to console 

`amixer get Master`

**Comment by ascrutae** [comment]
thanks. it works
