### ISSUE TITLE
powerarrow-darker: ALSA widget configuration

### ISSUE THREAD

**Issue by fislor** [copycat-killer/awesome-copycats#111]
When awesome is started, using rc.lua.powerarrow-darker, i got an error message:

"rc.lua:230: attempt to compare nil with number"

Im at 37be9eb9

**Comment by copycat-killer** [comment]
In 37be9eb, default line 230 in powerarrow-darker is [this one](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.powerarrow-darker#L230), which does not do a number comparison.

Paste me your `rc.lua`.

**Comment by copycat-killer** [comment]
Maybe you have [this issue](https://github.com/copycat-killer/lain/issues/185).

**Comment by fislor** [comment]
I have this one:

$ amixer
Simple mixer control 'IEC958',0

Tryed to add it in rc.lua and lain/widgets/alsabar.lua, but the problem remains.

**Comment by copycat-killer** [comment]
Your ALSA is off, as reported by `amixer`.

This is because Unity is a DE and loads the sound too, Awesome is only a WM and lets the user decide how to manage the environment.

Check [this guide](http://itsfoss.com/fix-sound-ubuntu-1304-quick-tip/) on how to start ALSA, or google for other solutions.

Once you've fixed it, check `amixer` again. If it outputs something like this:

```shell
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 1297 [2%] [off]
  Front Right: Playback 1297 [2%] [off]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 65536
  Front Left: Capture 65536 [100%] [on]
  Front Right: Capture 65536 [100%] [on]
```

then the audio is working, and if the first element shown (the playback one) is not called "Master" as usual, redefine `channel` within `lain.widgets.alsa`. Assuming you are using powerarrow-darker template, this is the modification:

```lua
-- ALSA volume
volicon = wibox.widget.imagebox(beautiful.widget_vol)
volumewidget = lain.widgets.alsa({
    channel  = "SetYourMasterChannelNameHere", 
    settings = function()
        if volume_now.status == "off" then
            volicon:set_image(beautiful.widget_vol_mute)
        elseif tonumber(volume_now.level) == 0 then
            volicon:set_image(beautiful.widget_vol_no)
        elseif tonumber(volume_now.level) <= 50 then
            volicon:set_image(beautiful.widget_vol_low)
        else
            volicon:set_image(beautiful.widget_vol)
        end

        widget:set_text(" " .. volume_now.level .. "% ")
    end
})
```

**Comment by fislor** [comment]
Thanks for the help, my problem was solved creating a file **~/.asoundrc** with this content:

pcm.!default {
	type hw
	card 1
	device 0
}
ctl.!default {
	type hw
	card 1
}

**Comment by sunny94** [comment]
I seem to have same issue as @fislor but not able to resolve it with this solution.

amixer output is
```
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',1
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
```
I'm using rc.lua.powerarrow-darker, and i'm getting error message:

"rc.lua:242: attempt to compare nil with number"

And, also what did you do after making a new asoundrc file ?
Did you restart or reinitialize alsa? Then how so?

Plz help me out, I'm a beginner here.

**Comment by sunny94** [comment]
@fislor 
My issue is very much similar to this issue

but the solution provided doesn't work for me

amixer output says
```
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',1
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
```
I have created a asoundrc file as specified in the #issue solution.

Do I need to restart or reinitialize alsa? and how can I do so?

Plz help me out, I'm a newbie and I've been struggling with this issue for a long time but not able to resolve it?
