### ISSUE TITLE
Error on theme multicolor

### ISSUE THREAD

**Issue by Xaviju** [copycat-killer/awesome-copycats#112]
Hi, thanks for your themes, are really awesome!

I'm using the theme ```multicolor``` and I am getting the following error:

```
bad argument #1 to 'strfind' (string expected, got FILE*)
```

Any ideas how to fix it?

**Comment by copycat-killer** [comment]
There's no `strfind` call in the theme, are you sure it's related to it?

Post a screenshot.

**Comment by Xaviju** [comment]
No, its not. Just discovered that was a ```lain``` problem. Sorry!

**Comment by copycat-killer** [comment]
Please be more clear. Is it a `lain` problem, or a configuration problem with `lain`?

**Comment by Xaviju** [comment]
Sorry, is a mistake. 
I've updated arch and suddenly I was receiving a lot of errors like this one. 
Since I made some changes on the LUA file (but I am not a lua developer) I thought it was my fault. I updated your theme repos and changed the theme to a clean one and stopped notifying errors. Then, the error appeared again.

The error is pointing to a lain file: ```/usr/share/awesome/lib/lain/util/dkjson.lua on line 397
So I guess is a line problem with the latest arch update and will be fixed soon.

Sorry again.

**Comment by copycat-killer** [comment]
It's more probably that you have a misconfiguration problem with some widgets using `dkjson`, like the weather one.

If you want to customize your setup, you are supposed to do it only via `rc.lua`, not hardcoding the sources, especially if you don't know Lua.

Tell me which changes did you made, and why. In the meantime, reinstall `lain` as well.
