### ISSUE TITLE
Pulseaudio widget exemple?

### ISSUE THREAD

**Issue by mnivoliez** [copycat-killer/awesome-copycats#113]
Hello, first i really love all that work (seriously, that's awesome). Yet, a sample of the use of pulseaudio widget should be great. I try to display it but no clue what i'm missing.

**Comment by copycat-killer** [comment]
This the multicolor widget template modified to work with pulseaudio:

```lua
-- PulseAudio volume
volumewidget = lain.widgets.pulseaudio({
    settings = function()
        vlevel = volume_now.left .. "-" .. volume_now.right .. "%"
        if volume_now.muted == "yes" then
            vlevel = vlevel .. " M"
        end

        widget:set_markup(markup("#7493d2", vlevel))
    end
})
```
Be always sure to read the wiki, it covers everything.
