### ISSUE TITLE
How to disable notifications about Wi-Fi in Multicolor-theme? 

### ISSUE THREAD

**Issue by dunnodun** [copycat-killer/awesome-copycats#114]
So I've recently switched to NetworkManager and it works nice with the Multicolor theme. But now the notifications about the Wi-Fi are not needed anymore and I want to get rid of them. Could somebody explain how to achieve this? 

Left is the notification I want to get rid of and right is the symbol of NetworkManager which makes the notifications useless. 
![Screenshot](http://i.imgur.com/qSMs8j5.jpg)

**Comment by copycat-killer** [comment]
From [lain wiki](https://github.com/copycat-killer/lain/wiki/net):

```lua
netupinfo = lain.widgets.net({
    notify = "off",
    settings = function()
        -- [...]
    end
})
```

**Comment by dunnodun** [comment]
Thank you very much!
