### ISSUE TITLE
simple way to create a widget

### ISSUE THREAD

**Issue by daks** [copycat-killer/awesome-copycats#115]
Hello,

I'm using your packaged themes for awesome, and find them great. 
I now want to create a simple widget (to display the number of GNU screen sessions running in my session, just to not halt my computer when there are still some) and want to know which way to do this, which tool (awful, beautiful, lain...) would be the simpler, because I'm totally ignorant about lua and awesome ecosystem.

Thanks.

**Comment by copycat-killer** [comment]
Put this widget in your `rc.lua`:

```lua
screenwidget = lain.widgets.base({
    cmd = "screen -ls",
    settings = function()
        s = string.match(output, "([%a|%d]+)%s+Socket"):gsub("No", 0)    
        widget:set_text("Sessions: " .. s .. " ") -- customize here
    end
})
```

also, add it to a wibox. Read [here](https://awesome.naquadah.org/wiki/My_first_awesome) to know how.


Next time please use more appropriate channels, this request is completely off-topic here.

**Comment by daks** [comment]
Thanks. In fact, this channel was not an appropriate one but didn't know where to go to have an informed answer. (IRC maybe, SO not sure).

**Comment by copycat-killer** [comment]
> didn't know where to go to have an informed answer

When you have an question, this is your check list:

0. awesome wiki
1. google/forums
2. awesome IRC channel
3. awesome mailing list

generally you won't go past step 1.
