### ISSUE TITLE
quakeconsole does not work with my terminal

### ISSUE THREAD

**Issue by aviau** [copycat-killer/awesome-copycats#116]
Hello!

Is looks like quakeconsole does not play well with gnome-terminal.

When I set it to use gnome-terminal, the terminal never appears. This is not the case when I revert to using xterm.

Any ideas?

**Comment by copycat-killer** [comment]
`gnome-terminal` is a GTK based application, while `xterm` is X based.

Basically you have to set `argname`:

```lua
-- quake terminal
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({ app = "gnome-terminal", argname = "--name %s" })
end
```

Read [here](https://github.com/copycat-killer/lain/issues/211) and [here](https://github.com/copycat-killer/lain/wiki/Utilities#quake).

**Comment by aviau** [comment]
Thank you!
