### ISSUE TITLE
rc.lua.previous should not be tracked

### ISSUE THREAD

**Issue by paescuj** [copycat-killer/awesome-copycats#121]

**Comment by copycat-killer** [comment]
Uhm... it should never be tracked, even without this rule, but ok.

**Comment by paescuj** [comment]
Thanks for merging the pull request.

Since I simply checkout this repository locally and use it to keep track of any changes, there was always the following message after using the `switch-theme.sh` script:

`$ git status`
```
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	rc.lua.previous

nothing added to commit but untracked files present (use "git add" to track)
```

We ignore the rc.lua file, consequently we can also ignore the rc.lua.previous file, imo.

**Comment by copycat-killer** [comment]
FYI, that message is pretty obvious and unharmful: if you query `git` with `status`, of course it has to tell you which are untracked files, if present.

**Comment by paescuj** [comment]
Thanks, I'm aware of that :-)
Sorry, I did not express myself very well - instead of "rc.lua.previous should not be tracked" I should have written "ignore untracked rc.lua.previous"...
