### ISSUE TITLE
Backlight

### ISSUE THREAD

**Issue by kkragoth** [copycat-killer/awesome-copycats#123]
As a laptop user, I find it difficult that I can't regulate brightness level of my display. I wrote short key binding that uses os.execute("xbacklight -[dec|inc] 10") to work around this issue.

I could make a pull request that adds this key binding (alt/super + arrows) to every rc, however it requires xbacklight installed.

**Comment by copycat-killer** [comment]
Not everyone is a laptop user, plus not everyone wants to adjust that. This is a too personal setting, so I won't merge.

PS: [This](https://github.com/copycat-killer/lain/wiki/redshift) might be of interest.
