### ISSUE TITLE
Battery Widget

### ISSUE THREAD

**Issue by Exapiper** [copycat-killer/awesome-copycats#126]
Hello Luke,

I have been using your arrow-darker them for quite a long time now. I saw a few emails concerning the battery widget and thinkpads and such. 

I decided to try my hand at configuring the thinkpad widget to no success and also simply just to use your widget to enumerate the 2 batteries instead of 1. 

looking at the lua file your instructions say if you have 2 batteries to use the "batteries" variable and also use the "{"BAT*"}" if you have more than 1. 

I tried implementing the:
batteries = {"BAT*"}   in many different ways, and lua complains about concatenating, so I don't know. 

my batteries are called BAT0 and BAT1 but apparently I don't know how to write that into array or list variable.

Any help would be appreciated, and thankyou for your work.

**Comment by copycat-killer** [comment]
You have to define a table of strings. In your case, it should be:

```lua
batwidget = lain.widgets.bat({
    batteries = {"BAT0", "BAT1"},
    -- [...]
})
```

if this still causes you issues, scrot or paste me awesome error infos.

**Comment by Exapiper** [comment]
Thanks, apparently I was messing with the wrong file entirely... haha
I was in line 61 of the bat.lua trying to put that in...

Thanks :)

P.S Do you have a recommended LUA book?

**Comment by copycat-killer** [comment]
For your settings, you only have to deal with `rc.lua`.

> Do you have a recommended Lua book?

https://www.lua.org/pil/contents.html
