### ISSUE TITLE
Add titlebar icons for awesome-git

### ISSUE THREAD

**Issue by aajjbb** [copycat-killer/awesome-copycats#129]
Hi,

Newer versions of awesome (v4.0 is soon to be released) has 4 icons in clients titlebars. It would be nice if the themes implemented those icons as well.

**Comment by copycat-killer** [comment]
@aajjbb Copland already has titlebars, while previous themes weren't suppose to have them. We should create them from scratch, so any design idea or work is welcome.

**Comment by aajjbb** [comment]
Hi, I've been using titlebar icons from awesome theme 'zenburn', which comes by default with awesome install. They runs smooth with copycats themes. What do you think about using them ?

**Comment by copycat-killer** [comment]
OK, but I thought you wanted me to create a new set for each theme.

**Comment by aajjbb** [comment]
That's what I meant, I just pointed (maybe to other users) that it works okay with those icons too.

**Comment by copycat-killer** [comment]
Any design idea or work is still welcome then. 😃 

I'll postpone this after 4.0 port completion, anyway.
