### ISSUE TITLE
[multicolor theme] - Tasklist in middle of top bar makes right layout disappear

### ISSUE THREAD

**Issue by acama** [copycat-killer/awesome-copycats#136]
Hi,
I am using the multicolor theme and would like to have the tasklist on the top bar. I uncommented the line of code in the rc.lua to enabled the tasklist in the middle of the top bar. However, when I do this, the tasklist appears but now the right layout (with the cpu status, mem etc.)  disappears. Is there anyway to fix this ? I have been using the multicolor theme for over a year and a half (when I first cloned this repo). It seems like the themes were redesigned since then and now I am having issues like this...

**Comment by copycat-killer** [comment]
The themes were only updated to the new awesome branch.

It seems that you left `nil` uncommented after the tasklist. Of course you have to disable it, otherwise it will take the right layotbox place. To move the tasklist from bottom to top bar:

```diff
--- rc.lua.multicolor
+++ rc.lua.multicolor
@@ -396,8 +396,8 @@
             mpdicon,
             mpdwidget,
         },
-        --s.mytasklist, -- Middle widget
-        nil,
+        s.mytasklist, -- Middle widget
+        --nil,
         { -- Right widgets
             layout = wibox.layout.fixed.horizontal,
             wibox.widget.systray(),
@@ -435,7 +435,8 @@
         { -- Left widgets
             layout = wibox.layout.fixed.horizontal,
         },
-        s.mytasklist, -- Middle widget
+        --s.mytasklist, -- Middle widget
+        nil,
         { -- Right widgets
             layout = wibox.layout.fixed.horizontal,
             s.mylayoutbox,
```

**Comment by acama** [comment]
Thanks!
