### ISSUE TITLE
Force center dialog menus

### ISSUE THREAD

**Issue by evolvetoday** [copycat-killer/awesome-copycats#137]
New dialog windows not on center their parents (for example: dialog "save / dont save and close", app's options in a new windows, etc). I dont care about it in tiling mode, but in floating this is a trouble. How to force child windows (or ok, if not - all windows) center?

**Comment by copycat-killer** [comment]
All of my GTK/Java clients don't have such issue, so you have to help me reproducing it.

Post screenshots of current behaviour and desired one, plus instructions on how to reproduce an use case of particular interest.

Anyway, it's all about [rules](https://awesomewm.org/doc/api/libraries/awful.rules.html) on [clients](https://awesomewm.org/doc/api/classes/client.html). In particular, if you want to center any dialog on its parent window, you can start from a snippet like this:

```lua
    { rule_any = { type = { "dialog" } },
      callback = function(c)
          local parent = c:get_transient_for_matching(function(c2)
              return c2:is_transient_for(c)
          end)

          if parent then
              g = parent:geometry()
              -- set adjusted_geometry for c
              -- c:geometry(adjusted_geometry)
          end
      end
    },
```

**Comment by evolvetoday** [comment]
Oh, thanks, almost the thing I need: not centered, but bottom/right on parent window, not out of parent window.
One more dumb(?) question: how to create a rule for all windows to start on center of the screen?

**Comment by copycat-killer** [comment]
> how to create a rule for all windows to start on center of the screen?

```lua
    { rule = { },
      callback = function(c)
          if not awful.layout.getname():match("floating") then
			  for k,v in pairs(c.screen.all_clients) do
					 v.floating = false
			  end
              awful.layout.arrange(c.screen)
          end

          c.floating   = true
          local mg     = c.screen.geometry
          local mwfact = 0.5 -- change here as you like
          local g      = {}
          g.width      = math.sqrt(mwfact) * mg.width
          g.height     = math.sqrt(mwfact) * mg.height
          g.x          = mg.x + math.floor((mg.width - g.width) / 2)
          g.y          = mg.y + math.floor((mg.height - g.height) / 2)
          c:geometry(g)
      end
    },
```

This could be a recipe for the new [awesome site](https://github.com/awesomeWM/awesome-www).

**Comment by evolvetoday** [comment]
You're goddamn right :) Thanks a lot.
-- keep windows size:
_local mwfact = 0_
