### ISSUE TITLE
Space between system tray icons.

### ISSUE THREAD

**Issue by evolvetoday** [copycat-killer/awesome-copycats#138]
Is it possible to insert some space between system tray icons? They are so close to each other.

**Comment by copycat-killer** [comment]
[Yes](https://awesomewm.org/doc/api/classes/wibox.widget.systray.html#beautiful.systray_icon_spacing).

Please, [don't abuse](https://github.com/copycat-killer/awesome-copycats/blob/master/ISSUE_TEMPLATE.md#if-you-have-a-question) the issue format. Thanks.
