### ISSUE TITLE
Wrong submodule path

### ISSUE THREAD

**Issue by kazuoteramoto** [copycat-killer/awesome-copycats#140]
I'm getting this when trying to do a `git clone --recursive`
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:copycat-killer/awesome-freedesktop.git' into submodule path '/tmp/awesome-copycats/freedesktop' failed
```

I think `git@github.com:` must change to `git://github.com/`, right?

**Comment by copycat-killer** [comment]
You are trying to clone it with SSH. This is a public repository, you have to clone it with HTTPS.

[It's written in the readme.](https://github.com/copycat-killer/awesome-copycats#installation)

And it's found in the Issues section: #131 

Read the issue template, people!

**Comment by kazuoteramoto** [comment]
I just followed the readme:

`git clone --recursive https://github.com/copycat-killer/awesome-copycats.git`

(For anyone with the same problem, I fixed by using just clone and changing the `.gitmodules` and issuing `git submodule update --init --recursive`.)

Sorry to bother, I did not found that issue when searching, I try to avoid report issues.
