### ISSUE TITLE
Multiple bottom panels bug

### ISSUE THREAD

**Issue by padosucman** [copycat-killer/awesome-copycats#141]
1) $ awesome -v
 awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
OS: ArchLinux (fresh)

2)  -> expected behavior: 1 bottom panel
 -> actual behavior: 2, sometimes 3 panels with error when i try to click on any bottom panel. when i restart awesome - everything is ok even if i work ~3 hours. When i go away on 1-2 hours > the problem appears.
[Screenshot full](http://i.imgur.com/Q67IYQW.jpg)
[Screenshot with error](http://i.imgur.com/5CKzxsh.jpg)

*The same with a pure unedited "multicolor" config (lua.rc + theme.rc).*

3) -> steps to reproduce the problem
wait an hour and dont touch pc > profit! :) (when i just work - nothing happens, everything seems ok, no new duplicate bottom panels appears. _but not always_)

Help me please :)

**Comment by copycat-killer** [comment]
*[Closed by mistake]*

It's the Firefox rule asking for `awful.screen.focused()` in idle.

Try this one instead:

```lua
    -- Set Firefox to always map on the first tag on screen 1.
    { rule = { class = "Firefox" },
      properties = { screen = 1, tag = screen[1].tags[1] } },
```

Do you have a screensaver? Does your monitor automatically turn off? What exactly happens in idle mode?

@psychon Sorry to bother, but can you confirm that `awful.screen.focused()` working as expected here?

**Comment by psychon** [comment]
@copycat-killer The above code calls `awful.screen.focused()` when the config is loaded, not when the rule is applied. Also, assuming `awful.screen.focused()` returns some screen other than the first one, this code is trying to assign the client to e.g. a tag on screen 2, but also screen 1....??

The error message happens in a line with `c.screen = the_tag_that_awful_rules_found.screen`. So I guess that the error here is that the tag was already deleted and does no longer have a screen assigned. So, this needs some kind of "disconnect screen" RandR event. Perhaps suspending the computer?

I would propose to assign tags by name instead, i.e. `tag = "1"`. That will use "the given screen" from the rule and find a tag with this name on it.

CC @Elv13 just FYI that this kind of problem exists.

**Comment by padosucman** [comment]
I'll try it with this rule, thanks. Firefox was closed by the way. 
No,  I have no any screensavers installed and auto disable for monitor turned off. Even the monitor turned off. 

@psychon my tags named with unique words like "web"  "term"  "sys"

**Comment by psychon** [comment]
then `tag = "web"` or something like that.

**Comment by padosucman** [comment]
@copycat-killer @psychon 
Just found a clearly reproduce: switch monitor off > swtich monitor on : the bug. (even with fixed config)

**Comment by psychon** [comment]
Ok, since I have no clue of what this repo actually contains: What do I have to look at here? It sounds like something around `screen.connect_for_each_screen` or the `"added"` signal on screens.

**Comment by copycat-killer** [comment]
I am unable to reproduce. Does this happen also with `tag = "web"`?

I don't understand where the cause can be: except from widgets and wibar customizations, the themes are all alike.

Also, they don't differ much from the default `rc.lua`. The only notable difference may be [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.multicolor#L880-L890).

@padosucman Are you able to reproduce with a default multicolor setup, but with widgets code commented?

**Comment by padosucman** [comment]
When it happens Awesome automatically switch to the 1st tag ("web" for me) from any tag, and there no any windows (but they are opened) on all tags till i restart awesome.

**Comment by padosucman** [comment]
@copycat-killer the same with all themes + commented widgets.

**Comment by copycat-killer** [comment]
I can't help but asking [this question again](https://github.com/copycat-killer/awesome-copycats/issues/142#issuecomment-275198256).

In case the answer is no,  we need some stderr. If you have `exec awesome` in your `.xinitrc`, this is how you can get it:

```shell
startx -- -keeptty -nolisten tcp > $HOME/.xorg.log 2>&1'
```

**Comment by padosucman** [comment]
Anyway:
```bash
cat ~/.xorg.log
X.Org X Server 1.19.1
Release Date: 2017-01-11
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.8.14-1-ARCH x86_64 
Current Operating System: Linux cyl1zard 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-linux root=UUID=b5d4b4ba-0dbf-4195-ac9a-b47890593208 rw quiet
Build Date: 12 January 2017  07:11:40AM
 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu Jan 26 00:22:07 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
2017-01-26 00:22:08 /usr/share/awesome/lib/beautiful/xresources.lua:54: W: Failed to get xrdb value 'background'.
stack traceback:
	/usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:107: in function 'awful.hotkeys_popup.widget.new'
	/usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:460: in upvalue 'get_default_widget'
	/usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:477: in function 'awful.hotkeys_popup.widget.add_hotkeys'
	/usr/share/awesome/lib/awful/hotkeys_popup/keys/vim.lua:171: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/awful/hotkeys_popup/keys/init.lua:11: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/awful/hotkeys_popup/init.lua:12: in main chunk
	[C]: in function 'require'
	/home/buslique/.config/awesome/rc.lua:12: in main chunk
2017-01-26 00:22:08 W: beautiful: can't get colorscheme from xrdb (using fallback).
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
```

**Comment by psychon** [comment]
@copycat-killer How well did you test your code with multiple screens? If you have multiple screens, can you test it with some rounds of `xrandr --output FOO --off` and `xrandr --output FOO --auto`. It might also be worth to do the following (if Xorg does not reject it): Turn off your last output so that you end up with no output afterwards, i.e. `xrandr --output FOO --off ; sleep 10 ; xrandr --output FOO --auto`

@padosucman Please add the following to your config, (re)start awesome, turn your monitor off, wait a little, turn it on and get us the debug output. It sounds like your screen is actually removed when you switch off the monitor. That would be why so much state is lost.
```lua
screen.connect_signal("added", function(s) gears.debug.print_warning("added " .. gears.debug.dump_return{ s.outputs, s.geometry  }) end)
screen.connect_signal("removed", function(s) gears.debug.print_warning("removed " .. gears.debug.dump_return{ s.outputs, s.geometry  }) end)
screen.connect_signal("property::outputs", function(s) gears.debug.print_warning("outputs " .. gears.debug.dump_return{ s.outputs, s.geometry  }) end)
screen.connect_signal("property::geometry", function(s) gears.debug.print_warning("geometry " .. gears.debug.dump_return{ s.outputs, s.geometry  }) end)
```

**Comment by copycat-killer** [comment]
@psychon I don't have multiple screens at home, but I'll try as soon as I can get some. Even though, these configs are almost identical to the default one.

It may be useful to check if is there any relation with #142.

**Comment by Elv13** [comment]
This can be solved with https://awesomewm.org/apidoc/classes/screen.html#screen:fake_add from `awesome-client`. First, you create a couple of bash script to setup and undo multi monitor, Then your `Xephyr` can emulate multi-screen events correctly by calling those scripts. This is what I did for Tyrannical.

**Comment by padosucman** [comment]
@Elv13 thanks, but it's a bit difficult without working examples of bash and rc.lua scripts.

**Comment by Elv13** [comment]
There is an example in the link. You can use it (properly escape) like
`awesome-client 'thecode'`. Then just put that comand into a .sh and chmod
+x it. I don't the script around right now

**Comment by padosucman** [comment]
I switched hdmi cable from hdmi 2 to hdmi 1 port in monitor - seems like it was the reason. No bugs at all :) Anyway thanks for help guys!
