### ISSUE TITLE
NVIDIA ForceFullCompositionPipeline=on + Awesome UI artefacts

### ISSUE THREAD

**Issue by padosucman** [copycat-killer/awesome-copycats#142]
$ awesome -v
awesome v4.0 (Harder, Better, Faster, Stronger)
• Compiled against Lua 5.3.3 (running with Lua 5.3)
• D-Bus support: ✔
• execinfo support: ✔
• RandR 1.5 support: ✔
• LGI version: 0.9.1

_OS_: ArchLinux (fresh)
_Theme_: multicolor (upd: with all themes)
_Drivers_: nvidia 375.26 (not LTS) >> pacman -S nvidia nvidia-libgl
_Tail of 20-nvidia.conf_:

```bash
Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
     Identifier     "Monitor0"
     VendorName     "Unknown"
     ModelName      "LG Electronics IPS277"
     HorizSync       30.0 - 83.0
     VertRefresh     56.0 - 61.0
     Option         "DPMS"
 EndSection
 
 Section "Device"
     Identifier     "Device0"
     Driver         "nvidia"
     VendorName     "NVIDIA Corporation"
     BoardName      "GeForce GTX 760"
 EndSection
 
 Section "Screen"
     Identifier     "Screen0"
     Device         "Device0"
     Monitor        "Monitor0"
     DefaultDepth    24
     Option         "Stereo" "0"
     Option         "metamodes" "nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
     Option         "SLI" "Off"
     Option         "MultiGPU" "Off"
     Option         "BaseMosaic" "off"
     SubSection     "Display"
         Depth       24
     EndSubSection
 EndSection
 ```

-> expected behavior: no blinks at panels when **_ForceFullCompositionPipeline=On_**. 
-> actual behavior: both of panels blinks with artefacts ([screenshot](https://pp.vk.me/c626131/v626131062/4d0d8/TKKH9NXsCtg.jpg), can't catch the bug with screenshot, sorry for quality - bottom panel reflects a part of video from youtube and blinks even when I close video) only when I start any video (browser, mplayer, doesn't matter). 

There is no problem if set **_ForceFullCompositionPipeline_** to **_off_** but tearing.. you know)

-> steps to reproduce the problem
1) Install NVIDIA drivers > run nvidia-settings > X Server Display Configuration > Advanced > set checkmark ForceFullCompositionPipeline;
2) run any video on youtube > switch fullscreen > back to small screen = panels blinks
or
3) run any local video via any video player > switch fullscreen > back to small screen = panels blinks

**Comment by copycat-killer** [comment]
Very trivial question: does this happen with default `rc.lua` too?

Because I really don't understand how my relatively simple setups can do this, at the moment.

**Comment by padosucman** [comment]
Whoops, this happen with default rc.lua

**Comment by copycat-killer** [comment]
Then, fill an issue format in [awesome](https://github.com/awesomewm/awesome) repository.
