### ISSUE TITLE
add these two themes to the themes that you maintain?

### ISSUE THREAD

**Issue by SolarAquarion** [copycat-killer/awesome-copycats#155]
https://github.com/folcraed/dotfiles/tree/master/awesome/themes

**Comment by copycat-killer** [comment]
What's the problem with using @folcraed dots?

Anyway, this repository is now modular, and any pull request is welcome.

**Comment by SolarAquarion** [comment]
That could work since it was seemingly updated for Awesome 4.  Just tell me
what I need to change

On Feb 2, 2017 8:19 AM, "Luke Bonham" <notifications@github.com> wrote:

What's the problem with using @folcraed <https://github.com/folcraed> dots?

Anyway, this repository is now modular, and any pull request is welcome.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/copycat-killer/awesome-copycats/issues/155#issuecomment-276954831>,
or mute the thread

**Comment by copycat-killer** [comment]
> what I need to change

Add the new themes respecting the current modular structure. Just study how a theme is now written and loaded in order to add them.

**Comment by copycat-killer** [comment]
@SolarAquarion I just gave a closer look to the themes.

They are rather simple: just some colors and icons changed from the default.

Instead, I'd like to have more complex themes, including some new design ideas.

So I won't merge these, sorry. If you have a theme request, follow the issue format and be more specific.

**Comment by SolarAquarion** [comment]
Sure
