### ISSUE TITLE
Missing line in theme config

### ISSUE THREAD

**Issue by mathieufrh** [copycat-killer/awesome-copycats#158]
Look at this file, line 274: https://github.com/copycat-killer/awesome-copycats/blob/master/themes/multicolor/theme.lua#L274

I think that a line with ```awful.button({ }, 2, function () awful.layout.inc( 1) end),``` is missing.

**Comment by copycat-killer** [comment]
It's not.

Look at [the default rc.lua](https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua#L202), where the code is taken from.

Mouse button 2 stands for scrollclick: if you want, you can just add it.
