### ISSUE TITLE
vertex: dock wibox geometry issue on multiple screens

### ISSUE THREAD

**Issue by WillianPaiva** [copycat-killer/awesome-copycats#159]
i just set up to use the vertex theme but the doc wibox just respect the position x and y on 1 screen the others is like x and y is 0.

![example](https://cloud.githubusercontent.com/assets/2542886/22925648/cca2339c-f2a9-11e6-828f-c481f3c42211.png)

**Comment by copycat-killer** [comment]
Please try latest commit.

**Comment by WillianPaiva** [comment]
the problem still the same. what i found out by playin with 1 2 or 3 screens is that the latest screen is the only one with the dock on the right place. 
is like as a dock is inserted in a screen it messys up the geometry of the previous screens.  

a not really nice work around that i found out is to include:
```
s.myleftwibox.y = s.workarea.height/2 -dockheight/2
``` 
inside the 
```
s.docktimer:connect_signal("timeout", function()
``` 
at awesome start it is on the wrong place but after 2 seconds it reajusts to the proper position

**Comment by copycat-killer** [comment]
Try putting the `myleftwibox` code in a function to give to [`gears.timer.delayed_call`](https://awesomewm.org/doc/api/classes/gears.timer.html#gears.timer.delayed_call).

I'll do and test it as soon as I can, but in the meantime you could try yourself.

**Comment by copycat-killer** [comment]
@WillianPaiva I tried putting the vertical wibox code in a `gears.timer.delayed_call`. Please test it.

**Comment by WillianPaiva** [comment]
hey sry for the delay had some problem with latest update on arch. but any way i did test your code and still give the same result!!

**Comment by copycat-killer** [comment]
OK, seems definitely not an Awesome main loop related issue.

I guess putting

```lua
s.myleftwibox.y = s.workarea.height/2 - s.dockheight/2
```

after [this line](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/vertex/theme.lua#L350) gives you the same result.

The fact is, I just have one monitor, and I can only test via [`screen.fake_add`](https://awesomewm.org/doc/api/classes/screen.html#screen:fake_add), which works right here.

I need to know if you use a particular way to set your multiscreen environment; also, would be good to have the Awesome `stderr`, which you can fetch installing Xephyr and running 

```shell
$ cd ~/.config/awesome
$ Xephyr -screen 1920x1080 :5 & sleep 1 ; DISPLAY=:5 awesome -c rc.lua # adjust -screen as you like
```

**Comment by WillianPaiva** [comment]
sorry for the delay but doing what you said made it work but i actualy edited the theme to take out the dock as it was also creating problens when using fullscreens

**Comment by copycat-killer** [comment]
> sorry for the delay but doing what you said made it work

Can you be specific?

Also, how can I (try to) help you more?

**Comment by copycat-killer** [comment]
https://github.com/copycat-killer/awesome-copycats/issues/160#issuecomment-285937216
