### ISSUE TITLE
Multiple "create the wibox" in theme steamburn

### ISSUE THREAD

**Issue by dummys** [copycat-killer/awesome-copycats#161]
Hi,

Is it normal that  there is two time create the wibox code in the theme ?
I have also another problem, it seems that all in the bar is duplicated. I tried commenting the first wibox, same problem.
When I hide the client, the double writing disappear and the bar goes normal again.
![2017-02-23-23 24 58](https://cloud.githubusercontent.com/assets/1941445/23282319/e9ef8ae8-fa20-11e6-969d-f3c4983f47bc.png)

 ```
 -- Create the wibox
    s.mywibox = awful.wibar({ position = "top", screen = s, height = 18, bg = theme.bg_normal, fg = theme.fg_normal })

    -- Create the wibox
    s.mywibox = awful.wibar({ position = "top", screen = s, height = 18 })
```

**Comment by copycat-killer** [comment]
The to `wibox` codes were just a typo. Thanks for noticing.

In you screenshot, I see the tasklist in the wibox clearly working. Where is the duplication?

**Comment by dummys** [comment]
Just under the 'New Issue' you see a duplicated 'dummys@flashed' etc

**Comment by copycat-killer** [comment]
That's the titlebar, as you can tell by the 4 icons on the right too.

**Comment by dummys** [comment]
Yes but no, the title bar is the upper. Here is like a weird copy of the title bar, This wasnt here beforr, 

I dont know why is here... Look its awful. 



Sent from my mobile device









On Fri, Feb 24, 2017 at 11:40 PM +0100, "Luke Bonham" <notifications@github.com> wrote:












That's the titlebar, as you can tell by the 4 icons on the right too.

**Comment by copycat-killer** [comment]
> Title bar is useless right?

It's redundant, and wasn't enabled by default in 3.x branches, but some might like it.

Just remove it as I told.

**Comment by dummys** [comment]
Cool, solved. thanks
