### ISSUE TITLE
multiple wallpaper with multiple screen not working anymore

### ISSUE THREAD

**Issue by dummys** [copycat-killer/awesome-copycats#163]
Hi,

I updated my rc.lua and my theme.lua to the latest version and I got problem with the multiple wallpaper we already spoke together.

You told me to use this before: 

```lua
local function set_wallpaper(s)
    -- Wallpaper
    if beautiful.wallpaper then
    gears.wallpaper.maximized(beautiful.wallpaper[1], 1, true, {x = 10, y = 10})
        for s = 2, screen.count() do
            gears.wallpaper.centered(beautiful.wallpaper[s], s, beautiful.bg_normal)
        end
    end
end
```
and in the theme.lua: 

```lua
theme.wallpaper = { theme.dir .. "/wall2.png", theme.dir .. "/wall1.png" }
```

But it's not working anymore with the new rc.lua.
I tried a bunch of stuff but still not working.
Can you help me ?

Another finding in rc.lua.template:

```lua
-- No border for maximized clients
client.connect_signal("focus",
    function(c)
        if c.maximized then -- no borders if only 1 client visible
            c.border_width = 0
        elseif #awful.screen.focused().clients > 1 then
            c.border_width = beautiful.border_width
            c.border_color = beautiful.border_focus
        end
    end)
client.connect_signal("unfocus", function(c) c.border_color = beautiful.border_normal end)
-- }}}
```

is the #awful.screen a typo ?

Thanks a lot.

**Comment by copycat-killer** [comment]
Just keep `theme.wallpaper` as a string paths array, and replace [this line](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/multicolor/theme.lua#L262) with the following code in `theme.lua`:

```lua
gears.wallpaper.maximized(theme.wallpaper[1], 1, true, {x = 10, y = 10})
for s = 2, screen.count() do
    gears.wallpaper.centered(theme.wallpaper[s], s, beautiful.bg_normal)
end
```

> is the #awful.screen a typo?

No.

**Comment by dummys** [comment]
Ok thanks. 
What does the #?

**Comment by copycat-killer** [comment]
It's a counter.

**Comment by dummys** [comment]
ok. thanks

**Comment by dummys** [comment]
@copycat-killer seems it's still not working.
my Theme wallpaper: `theme.wallpaper                     = { theme.dir .. "/wall2.png", theme.dir .. "/wall1.png" }`

and the modification you asked me: 
`-- {{{ Screen
-- Re-set wallpaper when a screen's geometry changes (e.g. different resolution)
screen.connect_signal("property::geometry", function(s)
    -- Wallpaper
    if beautiful.wallpaper then
        local wallpaper = beautiful.wallpaper
        -- If wallpaper is a function, call it with the screen
        if type(wallpaper) == "function" then
            wallpaper = wallpaper(s)
        end
        -- gears.wallpaper.maximized(wallpaper, s, true)
        if s.index == 1 then
            gears.wallpaper.maximized(theme.wallpaper[s], s, true, {x = 10, y = 10})
        else
            gears.wallpaper.centered(theme.wallpaper[s], s, theme.bg_normal)
        end
    end
end)`
Get this error now: /usr/share/awesome/lib/gears/surface:90 cairo.surface: not directly instantiable

**Comment by copycat-killer** [comment]
@dummys I sure it's some misconfiguration, but I can't help you if you don't provide me some `stderr`.

**Comment by dummys** [comment]
Hmm which stderr you want ? There is no error in fact. The left screen is just black

**Comment by dummys** [comment]
@copycat-killer I did the test with latest version of awesome-copycats directly from git. Still black screen.

`ls
icons  theme.lua  wall1.png  wall2.png  wall.png
`
theme.lua:
`theme.zenburn_dir                               = require("awful.util").get_themes_dir() .. "zenburn"
theme.dir                                       = os.getenv("HOME") .. "/.config/awesome/themes/steamburn"
theme.wallpaper                                 = { theme.dir .. "/wall2.png", theme.dir.. "/wall1.png" }
theme.font                                      = "Misc Tamsyn 10.5"
...


function theme.at_screen_connect(s)
    -- Quake application
    s.quake = lain.util.quake({ app = awful.util.terminal })

    -- If wallpaper is a function, call it with the screen
    if type(theme.wallpaper) == "function" then
        theme.wallpaper = theme.wallpaper(s)
    end
    -- gears.wallpaper.maximized(theme.wallpaper, s, true)
if s.index == 1 then
    gears.wallpaper.maximized(theme.wallpaper[s], s, true, {x = 10, y = 10})
else
    gears.wallpaper.centered(theme.wallpaper[s], s, theme.bg_normal)
end
    -- Tags
    awful.tag(awful.util.tagnames, s, awful.layout.layouts)

    -- Create a promptbox for each screen
    s.mypromptbox = awful.widget.prompt()

`

**Comment by copycat-killer** [comment]
The black screen seems to be a file not found issue.

I see you're using `theme.zenburn_dir`, but then you have `theme.dir` in `theme.wallpaper`: are you sure your paths are set correctly?
 
> Hmm which stderr you want ? There is no error in fact. The left screen is just black

The `stderr` from Awesome, not the one you might get from `naughty` notifications.

You can get the `stderr` starting X like [this](https://github.com/copycat-killer/dots/blob/master/.bashrc#L51), then reading `~/.xorg.log`.

**Comment by dummys** [comment]
What about zenburn theme ? This line is in your vanilla theme.lua: https://github.com/copycat-killer/awesome-copycats/blob/master/themes/steamburn/theme.lua#L15

**Comment by dummys** [comment]
The code you give to me is working on your side?

**Comment by copycat-killer** [comment]
That line is there because I use zenburn icons for the titlebar.

Try doing this:

```lua
theme.wallpaper = theme.dir .. "/wall1.png"
theme.wallpaper2 =  theme.dir.. "/wall2.png"

-- [...]

function theme.at_screen_connect(s)
    -- Quake application
    s.quake = lain.util.quake({ app = awful.util.terminal })

    -- If wallpaper is a function, call it with the screen
    if type(theme.wallpaper) == "function" then
        theme.wallpaper = theme.wallpaper(s)
    end
    -- gears.wallpaper.maximized(theme.wallpaper, s, true)
    if s.index == 1 then
        gears.wallpaper.maximized(theme.wallpaper, s, true, {x = 10, y = 10})
    else
        gears.wallpaper.centered(theme.wallpaper2, s, theme.bg_normal)
    end

    -- [...]
```

**Comment by dummys** [comment]
tested on my laptop but with only 1 screen. Seems to works. Will test it monday with my dual screen and come back here to tell you result.
Anyway thanks for helping me fixing those lame bug :D

**Comment by dummys** [comment]
ok tested @ work with multiple screen. It works. thanks a lot.
