### ISSUE TITLE
is awesome 4.0 required?

### ISSUE THREAD

**Issue by ckozler** [copycat-killer/awesome-copycats#164]
I have tried researching this already and it looks like maybe awful.spawn is not in 3.5? I am on Fedora 24 with 3.5.2 and when I tried to load these rc.lua's they error out saying module awful.spawn is not found and thus it breaks. I tried changing the requires in helpers.lua to read awful.util.spawn per a tip here - https://www.reddit.com/r/awesomewm/comments/5th3tp/awfulspawn_issues/ - but this didnt work either

Any ideas?

**Comment by copycat-killer** [comment]
Yes, Awesome 4.x is required, as written in the readme.

**Comment by ckozler** [comment]
I completely skipped over that not realizing it was right in the header. I noticed your other posts on lain and freedesktop saying it was unsupported however I think it would be ideal to update the readme and say that 3.5 is completely unsupported. The idea I had based on notes in lain and freedesktop repo was to go and revert and then figured it would work - which it of course did not :-)

**Comment by copycat-killer** [comment]
> I think it would be ideal to update the readme and say that 3.5 is completely unsupported. 

[This](https://github.com/copycat-killer/awesome-copycats#themes-for-awesome-wm-4x) is clear enough, as long as you read it.

> The idea I had based on notes in lain and freedesktop repo was to go and revert and then figured it would work - which it of course did not :-)

[b0ab0d7](https://github.com/copycat-killer/awesome-copycats/commit/b0ab0d7837987be81b9195a36631df773113d491) is the last 3.5.x related commit.
