### ISSUE TITLE
Using steamburn and cycling through the layout, the client are not rearranging

### ISSUE THREAD

**Issue by dummys** [copycat-killer/awesome-copycats#167]
Hello,

Using the default configuration of rc.lua, commenting the line for the firefox rule and choosing theme steamburn, when I open let's say two firefox and I cycle through the layout, the tiling get not applied.
When I do the same with let's say pinta, it's the same. When I do the same with rxvt, it's working, with zathura it's working too.Chromium is not working too. Is it a bug of awesome or it's normal ? Or is a bug in the rc.lua ?
It's working in your environment ? It's a GTK bug ? Pinta and firefox use GTK, but what about chromium ?

**Comment by copycat-killer** [comment]
You need to see if you have rules applied on those clients: if you have a maximized client, even if you cycle layouts, it'll remain maximized until you unmaximize it, of course.

Also, try with `/etc/xdg/awesome/rc.lua` and see if you still experiences the same behaviour.

**Comment by dummys** [comment]
I have no rules other that the one you have setup in your template. I also commented the rule for firefox.

**Comment by copycat-killer** [comment]
Did you do this?

> try with `/etc/xdg/awesome/rc.lua`

**Comment by dummys** [comment]
Yes I get the same problem. I get this problem on laptop but not on desktop in fact.
Tried with the original rc.lua, put two firefox in tiling mode and they didn't tile. I open two more lxterminal, they follow the tile but firefox still not.

**Comment by copycat-killer** [comment]
I don't know, but since you confirmed that this happens with default `rc.lua`, then it's out of this scope.

You have to ask [Awesome community](https://awesomewm.org/community).
