### ISSUE TITLE
There is no network activity for Multicolor theme

### ISSUE THREAD

**Issue by mtkaplanoglu** [copycat-killer/awesome-copycats#170]
Hi, 

In the multicolor theme, there is no network activity when i connect to wifi. Also, could you add "Mb/s" or "kb/s" definitions to activity monitor ?

Regards,

**Comment by copycat-killer** [comment]
> there is no network activity when i connect to wifi

Read [here](https://github.com/copycat-killer/lain/wiki/net#setting-iface-manually).

> could you add "Mb/s" or "kb/s" definitions to activity monitor ?

[Customize it](https://github.com/copycat-killer/lain/wiki/net) yourself.
