### ISSUE TITLE
Layout not changing in tags > 5 

### ISSUE THREAD

**Issue by enstrophy** [copycat-killer/awesome-copycats#173]
> ```awesome -v```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

>  ```lua -v```
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

When you increase the number of tags to 9 by replacing line 71 of rc.lua
by ```awful.util.tagnames = { "1", "2", "3", "4", "5", "6", "7", "8", "9" }```
in place of ```awful.util.tagnames = { "1", "2", "3", "4", "5" }```,
I am unable to change layout in tags 6-9.

The theme I am using is *powerarrow*, though same issue persists with all other themes.
Its working as expected with default *rc.lua* and also with the
default *theme.lua* instead of the one in *powerarrow*.
So I guess some setting in the *theme.lua* folder is causing the issue.
Other functions like run prompt, restart awesome, launching terminal 
etc. are working on tags 6-9.

**Comment by copycat-killer** [comment]
Just uncomment more layouts [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.template#L72).

**Comment by enstrophy** [comment]
**Thanks, that worked.**
So number of layouts should always be greater than number of tags I suppose.

**Comment by copycat-killer** [comment]
No, number of layouts should always match your preference.

**Comment by enstrophy** [comment]
So is there any way I can keep the original 5 layouts only and all 9 tags?

**Comment by copycat-killer** [comment]
You can switch layouts with default `mod4 + space`, and [set specific per-tag layouts](https://awesomewm.org/doc/api/libraries/awful.layout.html#set), or just duplicate layout names in the table above to mach specifig tags.

You can also use [dynamic tagging](https://github.com/copycat-killer/lain/wiki/Utilities#dynamic-tagging) to [add](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.template#L305) and [remove](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.template#L309) tag with specific layouts as you like.

**Comment by Emptyfruit** [comment]
Can you explain why this is so? If i leave only 2 layouts in my list, they work only on first 2 tags. That should be absolutely irrelevant, or am i missing smth?

**Comment by fcevado** [comment]
@Emptyfruit actually the layout is incremented by default through the tags list. Just see:
https://github.com/copycat-killer/awesome-copycats/blob/master/themes/multicolor/theme.lua#L265
that happens with every theme, you can just set a fix layout for all the tags:
` awful.tag(awful.util.tagnames, s, awful.layout.layouts[0])`
