### ISSUE TITLE
Layouts don't seem to work properly

### ISSUE THREAD

**Issue by jhaagmans** [copycat-killer/awesome-copycats#176]
`awesome -v 
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1`
`lua -v
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio`

When using the rc.lua from this repo, if I press MOD4+enter (for instance), a new terminal window (either `xterm` or `urxvt`) opens as a small floating window in the top left corner. I only have the "tile" layout enabled in `rc.lua`. It happens with all themes and does **not** happen when switching back to the original (default) `rc.lua`. Switching the layout of the individual window does not change anything, apart from it being draggable when it's in `floating` mode.

Is this in any way expected behaviour or maybe a setting somewhere? I only want to use tiling for everything (which is why I only enabled 1 layout).

**Comment by speedlight** [comment]
Maybe check de awful.rules of the theme.

**Comment by jhaagmans** [comment]
There are no rules defined for this theme (in "vanilla" `powerarrow-dark`).

**Comment by copycat-killer** [comment]
Specify `awful.layout.suit.tile` for every tag [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.template#L72). That is, there must be a bijection.

Example:

```lua
awful.util.tagnames = { "I", "want", "only", "tiles" } -- 4 tags
awful.layout.layouts = { -- 4 layouts
    awful.layout.suit.tile,
    awful.layout.suit.tile,
    awful.layout.suit.tile,
    awful.layout.suit.tile,
}
-- if #layouts < #tagnames, awesome will assume floating for non specified layouts 
```

**Comment by jhaagmans** [comment]
Well, that seemed to have fixed this issue. I've had an Awesome 3 setup before where this was not necessary. Is this an Awesome 4 issue or does it have something to do with `awesome-copycats`?
