### ISSUE TITLE
Awful.spawn not found

### ISSUE THREAD

**Issue by mathiasmah** [copycat-killer/awesome-copycats#180]
I'm using  the commit for Awesome WM 3.5+.

When I start awesome i get the fallowing error: 

error: /home/mathias/.config/awesome/lain/helpers.lua:10: module 'awful.spawn' not found:
	no field package.preload['awful.spawn']
	no file './awful/spawn.lua'
	no file '/usr/local/share/lua/5.1/awful/spawn.lua'
	no file '/usr/local/share/lua/5.1/awful/spawn/init.lua'
	no file '/usr/local/lib/lua/5.1/awful/spawn.lua'
	no file '/usr/local/lib/lua/5.1/awful/spawn/init.lua'
	no file '/usr/share/lua/5.1/awful/spawn.lua'
	no file '/usr/share/lua/5.1/awful/spawn/init.lua'
	no file '/home/mathias/.config/awesome/awful/spawn.lua'
	no file '/home/mathias/.config/awesome/awful/spawn/init.lua'
	no file '/etc/xdg/xdg-awesome/awesome/awful/spawn.lua'
	no file '/etc/xdg/xdg-awesome/awesome/awful/spawn/init.lua'
	no file '/etc/xdg/awesome/awful/spawn.lua'
	no file '/etc/xdg/awesome/awful/spawn/init.lua'
	no file '/usr/share/awesome/lib/awful/spawn.lua'
	no file '/usr/share/awesome/lib/awful/spawn/init.lua'
	no file './awful/spawn.so'
	no file '/usr/local/lib/lua/5.1/awful/spawn.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/awful/spawn.so'
	no file '/usr/lib/lua/5.1/awful/spawn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './awful.so'
	no file '/usr/local/lib/lua/5.1/awful.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/awful.so'
	no file '/usr/lib/lua/5.1/awful.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

I'm aware that this version is no longer supported but I still hope someone can tell me what my mistake is. Do i miss some dependencies or something? 

awesome -v output is:

awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

**Comment by copycat-killer** [comment]
Propagate reversion to dependencies as well. As you can read [here](https://github.com/copycat-killer/awesome-copycats/tree/b0ab0d7837987be81b9195a36631df773113d491), for `lain` it's [301faf5](https://github.com/copycat-killer/lain/tree/301faf5370d045e94c9c344acb0fdac84a2f25a6), while for `freedesktop`, [2c695a9](https://github.com/copycat-killer/awesome-freedesktop/tree/2c695a922856e22d117cd80486d6ce67d79a72df).

**Comment by copycat-killer** [comment]
I am sure this is the fail, but if you need any more help, don't hesitate to reply back.
