### ISSUE TITLE
super+p launcher doesn't work

### ISSUE THREAD

**Issue by mahdiG** [copycat-killer/awesome-copycats#182]
If you can't find a solution and your issue doesn't happen with default configuration, then go ahead and provide:

* output of `awesome -v` and `lua -v`
awesome v4.0
lua 5.3.3

* expected behavior and actual behavior
super+p should launch a launcher but it doesn't.
* steps to reproduce the problem
Press super+p and nothing happens

**Comment by mahdiG** [comment]
I compared your rc.lua to the default one and realized that the menubar is commented in your config. So I added it myself and it works now. But why is it commented?

**Comment by copycat-killer** [comment]
Because `dmenu` is better, imho.

But users can always uncomment it back as you did.
