### ISSUE TITLE
[freedesktop/menubar] table index is nil

### ISSUE THREAD

**Issue by Kkaminski93** [copycat-killer/awesome-copycats#184]
/usr/share/awesome/lib/menubar/icon_theme.lua:95: Table index is nil

![error](https://user-images.githubusercontent.com/28407207/26844842-5b9e0036-4aba-11e7-8f9f-2467856c01b3.png)

**Comment by copycat-killer** [comment]
`menubar` is telling you that it can't find an icon theme. Install `hicolor` or `adwaita`.

If the problem still persists:

1. Give me the output of `awesome -v` and `lua -v`.

2. Enable `menubar` decommenting the relative lines in `rc.lua` and see if `mod4 + p` works.

**Comment by Kkaminski93** [comment]
This fixed the issue.. thanks for helping with my issue.
