### ISSUE TITLE
An attempt to call a nil value causes copland to crash with the Xserver.

### ISSUE THREAD

**Issue by Incognito4nonymous** [copycat-killer/awesome-copycats#185]
Reporting in !
An error is preventing the Copland theme to launch, it seems to be related to a call to beautiful ?
I'm having trouble to see what it can be related to cause my terminal is flooded by X errors. :fearful:

**Comment by copycat-killer** [comment]
Copland is working fine here, I can't help you if you don't provide me with some log.

Start X [like I do](https://github.com/copycat-killer/dots/blob/master/.bashrc#L52): when it crashes, it'll print errors in `~/.xorg.log` file instead of tty. Paste me that file.

**Comment by Incognito4nonymous** [comment]
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Sat Jun 10 17:34:35 2017
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
2017-06-10 17:34:37 /usr/share/awesome/lib/beautiful/xresources.lua:84: W: Failed to get xrdb value 'Xft.dpi'.
stack traceback:
	/usr/share/awesome/lib/beautiful/init.lua:119: in upvalue 'load_font'
	/usr/share/awesome/lib/beautiful/init.lua:138: in local 'set_font'
	/usr/share/awesome/lib/beautiful/init.lua:219: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/beautiful.lua:5: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/awful/tag.lua:12: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/awful/layout/init.lua:19: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/awful/init.lua:42: in main chunk
	[C]: in function 'require'
	/home/incognito/.config/awesome/rc.lua:14: in main chunk
2017-06-10 17:34:37 W: awful: function spawn_with_shell is deprecated, see awful.spawn.with_shell.
stack traceback:
	/usr/share/awesome/lib/gears/debug.lua:91: in function 'gears.debug.deprecate'
	/usr/share/awesome/lib/awful/init.lua:28: in function 'awful.util.spawn_with_shell'
	/home/incognito/.config/awesome/rc.lua:55: in local 'run_once'
	/home/incognito/.config/awesome/rc.lua:64: in main chunk
2017-06-10 17:34:37 W: awful: function spawn_with_shell is deprecated, see awful.spawn.with_shell.
stack traceback:
	/usr/share/awesome/lib/gears/debug.lua:91: in function 'gears.debug.deprecate'
	/usr/share/awesome/lib/awful/init.lua:28: in function 'awful.util.spawn_with_shell'
	/home/incognito/.config/awesome/rc.lua:56: in local 'run_once'
	/home/incognito/.config/awesome/rc.lua:64: in main chunk
2017-06-10 17:34:37 W: awful: function spawn_with_shell is deprecated, see awful.spawn.with_shell.
stack traceback:
	/usr/share/awesome/lib/gears/debug.lua:91: in function 'gears.debug.deprecate'
	/usr/share/awesome/lib/awful/init.lua:28: in function 'awful.util.spawn_with_shell'
	/home/incognito/.config/awesome/rc.lua:58: in local 'run_once'
	/home/incognito/.config/awesome/rc.lua:64: in main chunk
2017-06-10 17:34:37 W: awful: function spawn_with_shell is deprecated, see awful.spawn.with_shell.
stack traceback:
	/usr/share/awesome/lib/gears/debug.lua:91: in function 'gears.debug.deprecate'
	/usr/share/awesome/lib/awful/init.lua:28: in function 'awful.util.spawn_with_shell'
	/home/incognito/.config/awesome/rc.lua:59: in local 'run_once'
	/home/incognito/.config/awesome/rc.lua:64: in main chunk
2017-06-10 17:34:37 W: awful: function spawn_with_shell is deprecated, see awful.spawn.with_shell.
stack traceback:
	/usr/share/awesome/lib/gears/debug.lua:91: in function 'gears.debug.deprecate'
	/usr/share/awesome/lib/awful/init.lua:28: in function 'awful.util.spawn_with_shell'
	/home/incognito/.config/awesome/rc.lua:60: in local 'run_once'
	/home/incognito/.config/awesome/rc.lua:64: in main chunk

(roxterm:784): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « mist »

(roxterm:784): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « mist »
/home/incognito/.themes/cyan1/gtk-2.0/gtkrc:1703: error: unexpected string constant "GimpRuler*", expected character '='

(gkrellm:792): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « mist »

(gkrellm:792): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « mist »
/home/incognito/.themes/cyan1/gtk-2.0/gtkrc:1703: error: unexpected string constant "GimpRuler*", expected character '='
xscreensaver: 17:34:38: already running on display :1 (window 0xa00001)
 from process 779 (incognito@roswell).
2017-06-10 17:34:38 E: Error during a protected call: /home/incognito/.config/awesome/eminent/init.lua:18: attempt to call a nil value (global 'module')
stack traceback:
	/home/incognito/.config/awesome/eminent/init.lua:18: in main chunk
	[C]: in function 'require'
	/home/incognito/.config/awesome/themes/copland/theme.lua:13: in main chunk
	[C]: in function 'dofile'
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/beautiful/init.lua:184: in function 'beautiful.init.init'
	/home/incognito/.config/awesome/rc.lua:166: in main chunk
2017-06-10 17:34:38 E: beautiful: error loading theme file /home/incognito/.config/awesome/themes/copland/theme.lua

(gkrellm:809): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « mist »

(gkrellm:809): Gtk-WARNING **: Impossible de trouver le moteur de thème dans module_path : « mist »
/home/incognito/.themes/cyan1/gtk-2.0/gtkrc:1703: error: unexpected string constant "GimpRuler*", expected character '='
Jun 10 17:34 : socket: Failed to bind to '127.0.0.1:6600': Address already in use
Jun 10 17:34 : socket: Failed to bind to '127.0.0.1:6600': Address already in use

** (roxterm:784): WARNING **: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
  Impossible de charger l'image : /home/incognito/.gkrellm2/themes/CoplandOS/mail/decal_mail.png
  Impossible de charger l'image : /home/incognito/.gkrellm2/themes/CoplandOS/mail/decal_mail.png
error while running function!
stack traceback:
	/home/incognito/.config/awesome/rc.lua:205: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/incognito/.config/awesome/rc.lua:205: in main chunk
error: /home/incognito/.config/awesome/rc.lua:205: attempt to call a nil value (field 'at_screen_connect')
gkrellm: Sortie en raison de l'inactivation de l'option autorisant de multiples instances.

2017-06-10 17:34:39 W: awesome: a_glib_poll:389: Last main loop iteration took 0.119737 seconds! Increasing limit for this warning to that value.
2017-06-10 17:34:39 W: awesome: a_glib_poll:389: Last main loop iteration took 0.128329 seconds! Increasing limit for this warning to that value.
2017-06-10 17:34:40 W: awesome: a_glib_poll:389: Last main loop iteration took 0.936326 seconds! Increasing limit for this warning to that value.

**Comment by copycat-killer** [comment]
You had issues with `eminent`. 

Since you made me look at it, I realized the code was old. I removed the submodule and integrated its functionality directly into Copland `theme.lua`.

PS: replace `awful.util.spawn_with_shell` with `awful.spawn.with_shell` in your `rc.lua`.

**Comment by Incognito4nonymous** [comment]
Awesome bro ! This is flawless ! Sorry to have not answered earlier I just stumbled upon your reply.
Thanks again man !
