### ISSUE TITLE
Battery widget not showing if battery is charging - multicolor theme

### ISSUE THREAD

**Issue by canozo** [copycat-killer/awesome-copycats#187]
I noticed that on the [line 184](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/multicolor/theme.lua#L184) you use `bat_now.perc` instead of the local variable `perc` that is defined shortly before, so the widget only shows **"60"** instead of the desired **"60% plug"**.

**Comment by jackgu1988** [comment]
For me, even changing that does not solve the issue. I may have not configured something properly, however the battery percentage is showing correctly.

**Comment by copycat-killer** [comment]
@jackgu1988 You should not hardcode, but read lain wiki and properly do you setup.

**Comment by jackgu1988** [comment]
@copycat-killer I know but I am very busy at the moment to configure it properly. I will do when there is time.

Thank you very much anyway for the tip and the good work!

**Comment by copycat-killer** [comment]
@jackgu1988 You just need to define `ac = "ADP1" in your battery widget. An example with multicolor template: 

```lua
-- Battery
local baticon = wibox.widget.imagebox(theme.widget_batt)
local bat = lain.widget.bat({
    ac = "ADP1",
    settings = function()
        local perc = bat_now.perc ~= "N/A" and bat_now.perc .. "%" or bat_now.perc

        if bat_now.ac_status == 1 then
            perc = perc .. " plug"
        end

        widget:set_markup(markup.fontfg(theme.font, theme.fg_normal, perc .. " "))
    end
})
```

**Comment by jackgu1988** [comment]
@copycat-killer worked perfectly and saved me lots of time. Thanks a lot!
