### ISSUE TITLE
Calendar question...

### ISSUE THREAD

**Issue by ving2** [copycat-killer/awesome-copycats#190]
Hello.  What it could be? The picture attached.
![fff](https://user-images.githubusercontent.com/29830019/27767431-032cdb80-5f3b-11e7-9482-6e1b92554162.jpg)

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**Comment by copycat-killer** [comment]
If you had searched for "calendar" in the [issues section](https://github.com/copycat-killer/awesome-copycats/issues), you would have found the [solution already](https://github.com/copycat-killer/awesome-copycats/issues/186).
