### ISSUE TITLE
lain has wrong commit referenced

### ISSUE THREAD

**Issue by Kaukov** [copycat-killer/awesome-copycats#191]
When checking out the repo, it fails due to wrong lain commit referenced

```
error: Server does not allow request for unadvertised object adccf47bdf7a9023ad20d8d5dcdaf8bfa4c563ab
Fetched in submodule path 'lain', but it did not contain adccf47bdf7a9023ad20d8d5dcdaf8bfa4c563ab. Direct fetching of that commit failed.
```

Please fix it ^^

**Comment by florianrusch** [comment]
Hi, everybody,

a short workaround is to go into the lain folder and run this command: `git checkout head`

LG Florian

Am 7. Juli 2017 18:59:01 MESZ schrieb Kaukov <notifications@github.com>:
>When checking out the repo, it fails due to wrong lain commit
>referenced
>
>```
>error: Server does not allow request for unadvertised object
>adccf47bdf7a9023ad20d8d5dcdaf8bfa4c563ab
>Fetched in submodule path 'lain', but it did not contain
>adccf47bdf7a9023ad20d8d5dcdaf8bfa4c563ab. Direct fetching of that
>commit failed.
>```
>
>Please fix it ^^
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/copycat-killer/awesome-copycats/issues/191

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by copycat-killer** [comment]
@Kaukov Done.

**Comment by Wiles** [comment]
This is happening again:

```
error: Server does not allow request for unadvertised object 5e88adda33a905c51125cdf1affcbc7dd5ef45ab
Fetched in submodule path 'lain', but it did not contain 5e88adda33a905c51125cdf1affcbc7dd5ef45ab. Direct fetching of that commit failed.
```

**Comment by florianrusch** [comment]
did you try the workaround?

**Comment by Wiles** [comment]
Sorry should have mentioned that. The work around does fix it.

**Comment by lcpz** [comment]
Redone.
