### ISSUE TITLE
Adding widgets to a theme

### ISSUE THREAD

**Issue by lrargerich** [copycat-killer/awesome-copycats#194]
I'm trying to add a few widgets to the holo theme: 
File sys info
Memory Widget
Uptime 
etc.

I was trying to use vicious and I have added this to rc.lua

local vicious = require("vicious")

Then in the holo theme theme.lua I tried a simple example:

datewidget = wibox.widget.textbox()
vicious.register(datewidget, vicious.widgets.date, "%b %d, %R")

But this seems to make awesome unable to start (I wonder why).
Note this makes awesome unable to start even without adding the widget to a wibox.

Can you help me with a simple guide on how to add new widgets to one of the existing themes?

Thanks!

**Comment by copycat-killer** [comment]
With these configs, widgets have to be put in `theme.lua`.

Add other widgets [here](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/holo/theme.lua#L266) and put their definition (`datewidget`, in your example) [here](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/holo/theme.lua#L324).

**Comment by lrargerich** [comment]
That's exactly what I was doing but for some reason awesome refuses to start after adding the simple date widget.

**Comment by lrargerich** [comment]
Thank you very much. 
I managed to get the vicious memory widget working but I can't make it use the same fonts as my theme (holo)

Can you help me a little with this one? Then I will be able to add other vicious widgets to holo. 

This is the widget: (then I just add it to the wibox)

local memwidget  = wibox.widget.textbox()
vicious.cache(vicious.widgets.mem)
vicious.register(memwidget, vicious.widgets.mem, "$1% $5%", 13)

Holo is a bit different than the other themes in how widgets are handled and I couldn't find any examples of a vicious widget in holo.

**Comment by copycat-killer** [comment]
Not that I want to promote my library, but if you don't have a particular reason for using `vicious`, you could then use `lain`, which is also asynchronous. There's plenty of examples in other [themes](https://github.com/copycat-killer/awesome-copycats/tree/master/themes) you can just copy/paste in your custom Holo. Otherwise, check [here](https://github.com/Mic92/vicious) for a `vicious` manual.

**Comment by lrargerich** [comment]
Fair enough.
I would like a mem% swap% simple indicator, but from what I read in the lain documentation it only provides the number of MBs of memory used. Do you have a simple way to make it compute the percentages? Then I can use the lain widget and copy from some theme how to customize it.

Thanks!

**Comment by copycat-killer** [comment]
Try this.

```lua
local memory = lain.widget.mem {
    settings = function()
        local swap_perc = math.floor((mem_now.swap - mem_now.swapf) / mem_now.swap * 100)
        widget:set_markup(lain.util.markup.fontfg(theme.font, "#e0da37", -- customize this
        mem_now.perc .. "% " .. swap_perc .. "% "))
    end
}
```

The markup call makes it use your theme font. The hex olor will be its foreground color.

**Comment by lrargerich** [comment]
Thank you very much, two questions:

1. There is a 10% difference between the lain widget and the vicious widget for mem_now.perc, this is consistent so I wonder which one is wrong.
2. I'm trying to add the widget you sent me in holo where I need to put it in a box, so I added the following two lines (see below)

local memory = lain.widget.mem {
    settings = function()
        local swap_perc = math.floor((mem_now.swap - mem_now.swapf) / mem_now.swap * 100)
        widget:set_markup(lain.util.markup.fontfg(theme.font, "#FFFFFF", -- customize this
        mem_now.perc .. "% " .. swap_perc .. "% "))
    end
}
local membg = wibox.container.background(memory.widget, theme.bg_focus, gears.shape.rectangle)
local memwidget = wibox.containter.margin(membg, 0, 0, 5, 5)

But with these two lines awesome refuses to star so soemthing is wrong. I'm just trying to imitate what was done with the other widgets in the holo theme. Any ideas?

Thanks a lot for your help. Doing this alone would have been impossible...

**Comment by copycat-killer** [comment]
1. I don't know about `vicious`, but `lain` is aligned to `top` and `free -h`: https://github.com/copycat-killer/lain/issues/271
2. There's a typo: contain**t**er. This is correct:

```lua
local memory = lain.widget.mem {
    settings = function()
        local swap_perc = math.floor((mem_now.swap - mem_now.swapf) / (mem_now.swap > 0 and mem_now.swap or 1) * 100)
        widget:set_markup(lain.util.markup.fontfg(theme.font, "#FFFFFF",
        mem_now.perc .. "% " .. swap_perc .. "% "))
    end
}

local membg = wibox.container.background(memory.widget, theme.bg_focus, gears.shape.rectangle)
local memwidget = wibox.container.margin(membg, 0, 0, 5, 5)
```

**Comment by lrargerich** [comment]
Thank you very much Luke. You helped me more than enough :)

**Comment by copycat-killer** [comment]
If you need any help in the future, remember you can always rely on the [community](https://awesomewm.org/community).
