### ISSUE TITLE
Setting default layout for tags

### ISSUE THREAD

**Issue by alx-k** [copycat-killer/awesome-copycats#195]
Apologies for posting this here, I did google and search around but couldn't find a way using your `rc.lua`, I thought this may be the most appropriate place to ask.

You define tags and layouts as follows (I've edited a bit):

    awful.util.tagnames = { "1", "2" }
    awful.layout.layouts = {
       awful.layout.suit.floating,
       awful.layout.suit.tile
    }

In this case, there are two tags and two layouts defined. Tag 1 will have floating layout and Tag 2 will have tile layout.

How can I go about providing both floating and tile layout, but have all tags default to tile.

If I modify the layouts array, that affects the layouts that are overall available, not the default layouts for the tags at the same array index position.

**Comment by copycat-killer** [comment]
In `rc.lua`, define your own layouts table as usual, like you did above. Then, in your `theme.lua`, when you [specify tags](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/multicolor/theme.lua#L265) in `at_screen_connect` function, don't pass the whole `awful.layout.layouts` table, but only the entry you want as default for all tags. For instance, considering that `tile` is the second entry in your table, all you have to do is this:

```diff
-awful.tag(awful.util.tagnames, s, awful.layout.layouts)
+awful.tag(awful.util.tagnames, s, awful.layout.layouts[2])
```

**Comment by kawsar-prog** [comment]
It is also possible to set different layout for each tag. First , define a new layout table in `rc.lua` with a different name from the first one(e.g. `awful.layout.layouts2`). Then in `theme.lua`  replace the following line
`awful.tag(awful.util.tagnames, s, awful.layout.layouts)`  with `awful.tag(awful.util.tagnames, s, awful.util.layout.layouts2)` line.
