### ISSUE TITLE
beautiful.at_screen_connect(s) is nil value

### ISSUE THREAD

**Issue by Wonskcalb** [copycat-killer/awesome-copycats#198]
Hello there,

After deciding that my config was hiding a lot of rust, I reinstalled a fresh copy of awesome-copycats and I ended up with a nil value at line 199 in rc.lua : ` beautiful.at_screen_connect(s) is nil value`

It seems to be working for a lot of people straight out of the box, but not for me. Yet, it doesn't look that my beautiful lib is not differing much from yours. But I was able to fix that by changing the line to 
```lua
beautiful.get().at_screen_connect(s)
```

Am I the only one to have this problem, or should this be patched (maybe by providing beautiful as a git submodule) like lain and freedesktop ?

**Comment by copycat-killer** [comment]
The screen `s` is null because something went wrong during its initialisation. I need:

1. the infos requested by the [issue template](https://github.com/copycat-killer/awesome-copycats/blob/master/ISSUE_TEMPLATE.md);
2. your error log.

For point 2, you have two ways:

* Restart X like this:
  ```shell
  startx -- -keeptty -nolisten tcp > $HOME/.xorg.log 2>&1
  ```
  the error will be output into `$HOME/.xorg.log`. Paste it here.
 
* If you don't want to close your X session, you can use [Xephyr](https://wikipedia.org/wiki/Xephyr):
  ```shell
  # set screen size as you like
  Xephyr :1 -screen 1280x800 2> stdout.txt & DISPLAY=:1 awesome
  ```

  Once started, you should immediately get the error: close the window (Mod4+Shift+c), and paste the file `stdout.txt` here. If somehow `stdout.txt` doesn't contain the log, restart Xephyr without `2> stdout.txt`, and paste the terminal stdout.

---

I'll update the issue template meanwhile.

**Comment by Wonskcalb** [comment]
Weird. it might have been because X wanted to restart. I works perfectly fine now with the upstream rc.lua. Sorry for the inconvenience :o

**Comment by darkin1** [comment]
I getting that same error

awesome -v 

```              
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1
```
.xorg.log

```
xauth: (stdin):2:  unknown command "b9478ffec031c8917034cb65524ec2c0"


X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux level3 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-112-generic.efi.signed root=UUID=1a597133-2200-4b03-b157-cc3b27595824 ro quiet splash vt.handoff=7
Build Date: 13 October 2017  01:57:05PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/dariusz/.local/share/xorg/Xorg.1.log", Time: Thu Feb 22 13:38:26 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/dariusz/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused

```


```
~/.config/awesome/rc.lua:214: attempt to call a nil value (field `at_screen_connect')


error while running function!
stact traceback
  ~/.config/awesome/rc.lua:214: in local 'func'
  /usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
  ~/.config/awesome/rc.lua:214: in main chunk
error: ~/.config/awesome/rc:214: attempt to call a nil value (field 'at_screen_connect')
```

Also, I found thread about issue

https://www.reddit.com/r/awesomewm/comments/7288xa/awfulscreenpadding/

I tried to add padding line in the `theme.lua` in function `connect_for_each_screen` but that didn't fix the issue.
Anny suggestion?

**Comment by lcpz** [comment]
Your tracebacks don't tell anything, so this is probably an error between X and Ubuntu.

Try starting X with sudoer permissions.

**Comment by pawel-zet** [comment]
Possibly you may find something helpful in `~/.xsession-errors`.
This is the place where my Ubuntu lightdm puts some errors during starting of awesome

**Comment by darkin1** [comment]
@lcpz 
better not, I did that already and it blocked my ubuntu user account
https://ubuntuforums.org/showthread.php?t=2190818

 @pawel-zet 
I checked, there are no any logs from xsession, awesome, etc. only logs from Thunar

**Comment by lcpz** [comment]
Remove `unclutter` from `run_once` input table and disable `fs` widget on line 217 of `theme.lua`.

This is your [issue](https://github.com/lcpz/lain/issues/387). I still have to figure out if this is related to LGI 0.9.2 or Gio 2.5.4. Maybe you can help doing what is [suggested](https://github.com/lcpz/lain/issues/387#issuecomment-366509509).

**Comment by darkin1** [comment]
I tried your suggestion. 
First I removed `unclutter` and I put a table, also I disabled `fs`. This worked like a charm.
Secondly (for testing purpose) I only disabled `fs` and it also was fine.

Also, I tried to upgrade Gio/GLib but it failed at `make` step. I got `No objects are given and no makefile found` so I gave up with this.

Also. I tried to disable `fs` widget for other themes but didn't work. So it seems that only work for `copland` theme.

**Comment by ryukinix** [comment]
~ same here in two machines, I'll  try the @lcpz tip

**Comment by lcpz** [comment]
@darkin1 @ryukinix The new implementation of `lain.widget.fs` requires Gio/Glib >= 2.5.4, which you evidently don't have in your distro, although this version is already a year old if I'm not mistaken (infact, they released 2.5.5 recently).

Ask your distro maitainers to update the package, or install it manually as reported above.

I'm going to update lain wiki about this.

**Comment by sondr3** [comment]
What exactly are the packages required? I installed ~glibc~ at 2.25.* and still got the same error, do I need to install the Gio package separately?

**Comment by lcpz** [comment]
@sondr3 `glibc` contains the C bindings for GLib, it's a totally different package. You have to install Glib 2.5.4 and LGI 0.9.2.
