### ISSUE TITLE
Vertex theme

### ISSUE THREAD

**Issue by swordfischer** [copycat-killer/awesome-copycats#53]
I'd really like to see an awesome theme based of [Vertex](http://horst3180.deviantart.com/art/Vertex-Theme-470663601).

Cheers!

**Comment by Incognito4nonymous** [comment]
Wow, it looks cool indeed.

**Comment by mkdk** [comment]
i have a question. on my first pc where ubuntu 16 install it's working perfect, but on second where ubuntu 14.04 LTS do not working at all... where can be problem?

**Comment by copycat-killer** [comment]
Who knows?

You didn't provide error logs, and your context is too general. But maybe it's just a misconfiguration.

**Comment by copycat-killer** [comment]
@swordfischer I highly doubt you still use Awesome, still I wanted to inform you that your request has been finally satisfied. This is also thanks to the 4.x API, which is more powerful.

**Comment by swordfischer** [comment]
Thanks! You're right, recently switched :( But I'll check this out for sure!

**Comment by Incognito4nonymous** [comment]
Everything's awesome man, you're awesome, works perfectly on my project, I'll show pictures of it tomorrow on my G+ page, here's a link if you're interested, stay tuned !
https://plus.google.com/109597312525054575387
For a more precise time it should be done around 6 PM International Time.

**Comment by RossComputerGuy** [comment]
Since there's an issue for this theme and I don't want to create a new issue about this, can I use the Vertex theme in the distro I'm developing?

**Comment by lcpz** [comment]
@RossComputerGuy Of course. As written in the [readme](https://github.com/lcpz/awesome-copycats#themes-for-awesome-wm-4x), anyone is free to use the work under the [BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.
