### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by frankred** [copycat-killer/awesome-copycats#73]
Hi,

your themes looks awesome. I wan't them to install but it is not working. If I start awesome the "default" theme is shown.

I did the installation description ```switch-theme.sh``` and my ```~/.config/awesome``` looks like this:

```
froth@froth:~/.config/awesome$ ll
total 284
drwxrwxr-x  7 froth froth  4096 Jan 29 11:39 ./
drwx------ 29 froth froth  4096 Jan 28 15:00 ../
drwxrwxr-x  2 froth froth  4096 Jan 29 11:25 eminent/
drwxrwxr-x  8 froth froth  4096 Jan 29 11:25 lain/
drwxrwxr-x  2 froth froth  4096 Jan 29 11:25 menugen/
-rw-rw-r--  1 froth froth 27325 Jan 29 11:39 rc.lua
-rw-rw-r--  1 froth froth 24395 Jan 29 11:23 rc.lua.blackburn
-rw-rw-r--  1 froth froth 26983 Jan 29 11:23 rc.lua.copland
-rw-rw-r--  1 froth froth 23980 Jan 29 11:23 rc.lua.dremora
-rw-rw-r--  1 froth froth 30417 Jan 29 11:23 rc.lua.holo
-rw-rw-r--  1 froth froth 27325 Jan 29 11:23 rc.lua.multicolor
-rw-rw-r--  1 froth froth 26796 Jan 29 11:23 rc.lua.powerarrow-darker
-rw-rw-r--  1 froth froth 24720 Jan 29 11:23 rc.lua.rainbow
-rw-rw-r--  1 froth froth 24534 Jan 29 11:23 rc.lua.steamburn
-rw-rw-r--  1 froth froth  4338 Jan 29 11:23 README.rst
drwxrwxr-x  2 froth froth  4096 Jan 29 11:25 scratchdrop/
-rwxrwxr-x  1 froth froth   944 Jan 29 11:23 switch-theme.sh*
drwxrwxr-x 10 froth froth  4096 Jan 29 11:25 themes/
``` 

awesome v3.4.15
ubuntu v14.10
 
Before I installed:
- alsa-utils
- curl
- imagemagick

and did this: https://wiki.ubuntu.com/Fonts#Enabling_Bitmapped_Fonts 

Maybe it's just a small step I forgot. Some help would be awesome ;)
Greets!

**Comment by loudcry** [comment]
>awesome v3.4.5
You need to update awesome because these themes require awesome 3.5+

**Comment by copycat-killer** [comment]
these themes require awesome 3.5+

As it's written in the readme.

There are several guides for Ubuntu users to install branch 3.5. A quick search suggests the following:

http://libsora.so/posts/awesome-3-5-install
http://linuxg.net/how-to-install-awesome-window-manager-3-5-5-on-ubuntu-linux-mint-pinguy-os-lxle-and-other-ubuntu-derivatives

**Comment by frankred** [comment]
Thank you that solved my problem ;)
