### ISSUE TITLE
[Bug] asyncshell

### ISSUE THREAD

**Issue by ImmanuelHaffner** [copycat-killer/awesome-copycats#75]
Hello,

I just clone the repo and tried to run it in awmtt. It gives the following error:

```
[string "asyncshell.deliver(N)"]:1: attempt to index global 'asyncshell' (a nil value)
```
where N is an id (digit).

By looking at `lain/asyncshell.lua` i figured that line 44-46 have a bad format, and the substitution of `'` is wrong.

Here is my proposed patch

``` lua
diff --git a/asyncshell.lua b/asyncshell.lua
index 4a01caa..8e9277a 100644
--- a/asyncshell.lua
+++ b/asyncshell.lua
@@ -41,11 +41,11 @@ function asyncshell.request(command, callback)
    local tmpfname = asyncshell.file_template .. id
    asyncshell.request_table[id] = { callback = callback }
    local req =
-      string.format("sh -c '%s > %s; " ..
+      string.format("sh -c \"%s\" > '%s'; " ..
                     'echo "asyncshell.deliver(%s)" | ' ..
                     "awesome-client' 2> /dev/null",
-                    string.gsub(command, "'", "'\\''"), tmpfname,
-                    id, tmpfname)
+                    string.gsub(command, "'", "\\'"):gsub('"', '\\"'),
+                    tmpfname, id, tmpfname)
    spawn(req, false)
    return id
 end
```

I googled around a bit to find the origin for that asyncshell stuff (couldnt find it though). It seems like some other repos on github contain the same bug.

Regards,
Immanuel

**Comment by copycat-killer** [comment]
First of all, you raised the issue in the wrong repo.

I tested with the Lua interpreter. 

Original:
```lua
> command = "command"
> tmpfname = "tmpfname"
> id = "1"
> mystring = string.format("sh -c '%s > %s; " ..
>>               'echo "asyncshell.deliver(%s)" | ' ..
>>               "awesome-client' 2> /dev/null",
>>               string.gsub(command, "'", "'\\''"), tmpfname,
>>               id, tmpfname)
> 
> print(mystring)
```
```shell
sh -c 'command > tmpfname; echo "asyncshell.deliver(1)" | awesome-client' 2> /dev/null
```
Your patch:
```lua
> mystring2 = string.format("sh -c \"%s\" > '%s'; " ..
>>                'echo "asyncshell.deliver(%s)" | ' ..
>>                "awesome-client' 2> /dev/null",
>>                string.gsub(command, "'", "\\'"):gsub('"', '\\"'),
>>                tmpfname, id, tmpfname)
> print(mystring2)
```
```lua
sh -c "command" > 'tmpfname'; echo "asyncshell.deliver(1)" | awesome-client' 2> /dev/null
```

Now, you can see the original is a correct shell call with command string operand, while your patch tries to separate the operand in single useless operations, plus leaving an open bracket after `awesome-client`.

The real fact is: `awmtt` is telling you it can't find `asyncshell` in its scope.

I don't know how that script works, but `asyncshell`is working fine, as you could verify by testing my stuff directly.

If somehow you'll have problems, feel free to raise an issue (in the *correct* repo) and I'll be happy to help you.
