### ISSUE TITLE
[FALSE] Holo theme produces errors 

### ISSUE THREAD

**Issue by RankoKohime** [copycat-killer/awesome-copycats#77]
I cloned the Git today, and tried to run the Holo theme, and it works, but I get errors spammed at a rate of 1 every two seconds.

[string "asyncshell.deliver(3)"]:1: attempt to index global 'asyncshell' (a nil value)

While I can tweak the rc.lua to my needs, I'm not proficient enough with LUA to figure out where the error actually lies.

**Comment by copycat-killer** [comment]
The "error" lies in the fact that you didn't read the wiki.

[Installation](https://github.com/copycat-killer/awesome-copycats#installation)

[Notes](https://github.com/copycat-killer/awesome-copycats#notes)
