### ISSUE TITLE
Battery Widget Not Working

### ISSUE THREAD

**Issue by InsidiousMind** [copycat-killer/awesome-copycats#78]
The battery widget is always on "N/A". 
I have ACPI installed, but alll acpi bat_now.perc ever returns is something like
Battery 0: Discharging, 35%, 01:18:48 remaining

?

**Comment by norpol** [comment]
(Not part of this project):
How about telling us these following outputs:
```
ls /sys/class/power_supply/
ls /sys/class/power_supply/BAT0/
cat /sys/class/power_supply/BAT0/power_now
cat /sys/class/power_supply/BAT0/status
```

**Comment by copycat-killer** [comment]
That means `BAT0` is not your battery file.

Read the [updated wiki](https://github.com/copycat-killer/lain/wiki/bat).

**Comment by InsidiousMind** [comment]
ahh ok :) Thanks!
