### ISSUE TITLE
sloppy focus with unclutter

### ISSUE THREAD

**Issue by r8b7xy** [copycat-killer/awesome-copycats#81]
Current setup leads to an error described in [this issue](https://github.com/awesomeWM/awesome/issues/202).
This is fix from [blueyed rc](https://github.com/blueyed/awesome/blob/sloppy-focus-skip-not-moved/awesomerc.lua.in).
```lua
-- enable sloppy focus
- c:connect_signal("mouse::enter", function(c)
-     if awful.layout.get(c.screen) ~= awful.layout.suit.magnifier
-         and awful.client.focus.filter(c) then
-         client.focus = c
-     end
- end)
- 
- if not startup and not c.size_hints.user_position
-    and not c.size_hints.program_position then
-     awful.placement.no_overlap(c)
-     awful.placement.no_offscreen(c)
- end

+ local sloppyfocus_last = {x=nil, y=nil, c=nil}
+ client.connect_signal("mouse::enter", function(c)
+     local mcoords = mouse.coords()
+     if awful.layout.get(c.screen) ~= awful.layout.suit.magnifier
+             and awful.client.focus.filter(c) then
+         -- Skip focusing the client if the mouse wasn't moved.
+         if (mcoords.x ~= sloppyfocus_last.x or mcoords.y ~= sloppyfocus_last.y)
+             and c ~= sloppyfocus_last.c then
+             client.focus = c
+             sloppyfocus_last.c = c
+         end
+     end
+     sloppyfocus_last.x = mcoords.x
+     sloppyfocus_last.y = mcoords.y
+ end)

**Comment by r8b7xy** [comment]
Only drawback - cursor unhide when I close last client over hidden cursor...

**Comment by copycat-killer** [comment]
This has been a trouble since forever!

I was too busy/lazy to check it out, thank you. (And thanks to @blueyed)

PS: for your drawback, try `unclutter -root`, otherwise read `man unclutter`.

**Comment by blueyed** [comment]
I am not sure if the check for the last client (`sloppyfocus_last.c`) is not doing more harm than good here - I am not using that part currently myself.

Anyway, you should probably also see the discussion on the PR for this (https://github.com/awesomeWM/awesome/pull/183), and keep it as a reference.
This might get fixed in awesome in a different way etc.

**Comment by r8b7xy** [comment]
Last change (blueyed@0438133) fix the cursor blinking from time to time.
``` lua
local sloppyfocus_last = {c=nil}
client.connect_signal("mouse::enter", function(c)
    if awful.layout.get(c.screen) ~= awful.layout.suit.magnifier
            and awful.client.focus.filter(c) then
        -- Skip focusing the client if the mouse wasn't moved.
        if c ~= sloppyfocus_last.c then
            client.focus = c
            sloppyfocus_last.c = c
        end
    end
end)
```

**Comment by blueyed** [comment]
@copycat-killer 
Please consider using the version from https://github.com/blueyed/awesome/commit/0438133dfc3fc699368e53df98b5f8f1f31e93bc for now (pasted above).

@r8b7xy 
Thanks for investigating and reporting back!

**Comment by copycat-killer** [comment]
Thank you guys! 

:dancers:
