### ISSUE TITLE
Lain bat widget not showing notifications while using Multicolor theme

### ISSUE THREAD

**Issue by jotamjr** [copycat-killer/awesome-copycats#82]
First of all thanks for this awesome copycats themes xD

I'm not sure if its an intended behavior or an issue, but at the moment the bat widget notifications for low and critical states are not showing up while using the multicolor theme.

This is caused due to assigning a string to the bat_now.perc variable forcing the tonumber() function to return "nil" (bat.lua:127) failing to evaluate properly the following conditions.

Using a different variable instead of bat_now.perc (patch below) in rc.lua.multicolor has fixed the issue for me.

Kind Regards!
Jotam

```
--- a/rc.lua.multicolor
+++ b/rc.lua.multicolor
@@ -180,11 +180,11 @@ baticon = wibox.widget.imagebox(beautiful.widget_batt)
 batwidget = lain.widgets.bat({
     settings = function()
         if bat_now.perc == "N/A" then
-            bat_now.perc = "AC "
+            bat_perc = "AC "
         else
-            bat_now.perc = bat_now.perc .. "% "
+            bat_perc = bat_now.perc .. "% "
         end
-        widget:set_text(bat_now.perc)
+        widget:set_text(bat_perc)
     end
 })
```

**Comment by copycat-killer** [comment]
Thank you.
