### ISSUE TITLE
gap in recently maximized client

### ISSUE THREAD

**Issue by r8b7xy** [copycat-killer/awesome-copycats#83]
Every time I change layout to maximized there are few pixels left freely from the bottom and right side of the client. Clients always maximize completely after switching focus to next client.
Just have a look what's on my screen:
![gap](http://i.imgur.com/MuTj1Pg.png)

**Comment by copycat-killer** [comment]
How exactly do I reproduce this?

**Comment by r8b7xy** [comment]
Two clients in the same tag tiled then use one of this key binding to set layout to maximized:
``` lua
    awful.key({ modkey,           }, "space",  function () awful.layout.inc(layouts,  1)  end),
    awful.key({ modkey, "Shift"   }, "space",  function () awful.layout.inc(layouts, -1)  end),

**Comment by copycat-killer** [comment]
I am trying to reproduce, but I can't see if I manage to.

[Scrot](http://i.imgur.com/0a9OvmC.png) (layout icon is wrong, but it really is `awful.layout.suit.max`)

Trivial question: does this happens with default theme too?

**Comment by r8b7xy** [comment]
I've just added `awful.layout.suit.max` to steamburn's layouts and fully reproduced this bug with latest git.

**Comment by copycat-killer** [comment]
Investigate in [these lines](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.steamburn#L666-698).

Try replacing `client.connect_signal("focus", function (c) ... )` with default one from standard `rc.lua`, or removing/adjusting "Arrange signal handler" section (maybe the fault is [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.steamburn#L689-690)).

**Comment by r8b7xy** [comment]
When i comment out this line mentioned in the post above:
``` lua
  elseif #clients == 1 or layout == "max" then
  c.border_width = 0
```
Gap is fixed, but now i wonder how to handle no borders in maximized layout or with only one client...

**Comment by copycat-killer** [comment]
That was the point of `c.border_width=0`.

I'll look for an equivalent but inoffensive hack.

**Comment by r8b7xy** [comment]
Maybe @blueyed will have any idea how to handle this.
Thanks in advance.

**Comment by blueyed** [comment]
Isn't this just `size_hints_honor` being not False?
http://awesome.naquadah.org/wiki/FAQ#How_to_remove_gaps_between_windows.3F

**Comment by r8b7xy** [comment]
It's already defined [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.steamburn#L585).

**Comment by copycat-killer** [comment]
Try using [awful.client.moveresize](https://awesome.naquadah.org/doc/api/modules/awful.client.html#moveresize):

```lua
-- {{{ Arrange signal handler
for s = 1, screen.count() do screen[s]:connect_signal("arrange", function ()
        local clients = awful.client.visible(s)
        local layout  = awful.layout.getname(awful.layout.get(s))

        if #clients > 0 then -- Fine grained borders and floaters control
            for _, c in pairs(clients) do -- Floaters always have borders
                if awful.client.floating.get(c) or layout == "floating" then
                    c.border_width = beautiful.border_width

                -- No borders with only one visible client
                elseif #clients == 1 or layout == "max" then
                    c.border_width = 0
                    awful.client.moveresize(0, 0, 2, 2, c)
                else
                    c.border_width = beautiful.border_width
                end
            end
        end
      end)
end
-- }}}
```
Adjust arguments and see if you can remove the gap.

**Comment by copycat-killer** [comment]
@r8b7xy Any news on this?

**Comment by r8b7xy** [comment]
I've switched back to bspwm but I will defintely check this solution in the following weekend.

**Comment by copycat-killer** [comment]
@r8b7xy I don't want to press you, but if you have any time to help me fix this, I'd be grateful.

**Comment by r8b7xy** [comment]
Sorry for my inactivity. I've just tried your solution from https://github.com/copycat-killer/awesome-copycats/issues/83#issuecomment-94140986 and everything works great. Gap is finally gone. Thanks for your commitment with this issue.

**Comment by blueyed** [comment]
Should be fixed in https://github.com/awesomeWM/awesome/pull/1191#issuecomment-256316477 for awesome 3.6 (not released).

**Comment by copycat-killer** [comment]
@blueyed Thanks for the info.

Version 3.6 seems a lot of fun! Can't wait for the release.

**Comment by blueyed** [comment]
@copycat-killer 
You're welcome to use Git master already.. :)

**Comment by copycat-killer** [comment]
@blueyed I know, but I always prefer stable/official release. ;)
