### ISSUE TITLE
All themes broken with lua 5.3 on Arch Linux

### ISSUE THREAD

**Issue by robotanarchy** [copycat-killer/awesome-copycats#85]
Hello,

I've just upgraded lua to 5.3 and now all awesome-copycat themes are broken. here's a screenshot of multicolor:

![2015-05-18-191733_1366x768_scrot](https://cloud.githubusercontent.com/assets/7833187/7687603/af53b47a-fd9e-11e4-8cbb-b64ec19e7575.png)

For affected arch users, here's how I've downgraded again:
* Remove the new lua52 package and take care which packages also get removed (such as nmap, you'd also need to downgrade them so they don't depend on lua52!): ```pacman -Rsc lua52```
* Downgrade these packages:
```
pacman -U /var/cache/pacman/pkg/lua-5.2.4-1-x86_64.pkg.tar.xz
pacman -U /var/cache/pacman/pkg/lua-lgi-0.8.0-2-x86_64.pkg.tar.xz
pacman -U /var/cache/pacman/pkg/awesome-3.5.6-1-x86_64.pkg.tar.xz
```
* Restart awesome, copycat themes should work again
* You might want to ignore these packages in your pacman.conf, until the copycat themes are fixed

Thanks for these great themes :+1:

**Comment by skry** [comment]
I don't have any of the themes in use, only useless gap. In addition to uselesstile etc, stock layouts  broke too. I have it defaulting to uselesstile and after the error, it does not matter which layout I use, all windows seem to float. I also had to downgrade vim.

**Comment by acyuta** [comment]
I fix it like this: https://github.com/copycat-killer/awesome-copycats/pull/86

**Comment by florian-wagner** [comment]
@acyuta, I cloned your fork but I still get the errors below:
![20150519114707](https://cloud.githubusercontent.com/assets/2799008/7700192/21c23e2c-fe1d-11e4-9f02-a18c6a871474.png)

**Comment by acyuta** [comment]
Now i don't know what is this.

**Comment by copycat-killer** [comment]
@robotanarchy @acyuta Can you try 3766fdd?

Be sure to update lain recursively too.

**Comment by acyuta** [comment]
@copycat-killer this work properly, but without replace(e.g.): 
```
-- module('menugen')   -- on 
local menugen = {}
..... <!- code-!> 
funciton menugen.build_menu()
..... <!- code-!> 
return menugen
```
doesn't work

**Comment by acyuta** [comment]
But in my current situation i have this error, when change layer:
/usr/share/awesome/lib/awful/layout/init.lua:88 attempt to perform arithmetic on a table value (local 'i')

**Comment by copycat-killer** [comment]
@acyuta I don't understand what you wrote in your first reply.

But seems to me that your `git pull` doesn't solve it completely.

**Comment by chrisnorthcott** [comment]
@acyuta @copycat-killer 
The Awful layout API seems to have changed, as this is what is in my init.lua

```lua
  --- Change the layout of the current tag.
  -- @param i Relative index.
  -- @param s The screen number. 
  -- @param[opt] layouts A table of layouts.
  function layout.inc(i, s, layouts)
```

The attempt to perform arithmetic on 'i' is, I assume, because the theme is expected to be first and the index second:

```lua
     awful.key({ modkey,           }, "space",  function () awful.layout.inc(layouts,  1)  end),
```

Obviously, with the current API, this should be

``lua
     awful.key({ modkey,           }, "space",  function () awful.layout.inc(1, n, layouts)  end),
```

I came here in search of a solution to this and my lua is not that great, but hopefully it's some kind of clue toward a workaround or fix.

**Comment by copycat-killer** [comment]
@chrisnorthcott I've got everything working again with latest commit. Did you try it?

**Comment by chrisnorthcott** [comment]
How long ago was it? I `git clone`d a few hours ago, if it was in that time then no. I should probably clone again for the "proper" fix. :)

**Comment by copycat-killer** [comment]
@chrisnorthcott `awful.layout.inc` did not change, as you can see in `/etc/xdg/awesome/rc.lua` too.

I found the problem was the localization line:

```lua
os.setlocale(os.getenv("LANG"))
```
and I removed in 3766fdd. 

It is very strange to me that you're having these issues, since there was really no change in awesome since january: it has only been compiled against Lua 5.3.

**Comment by chrisnorthcott** [comment]
Hmm. Running latest Awesome (from Git) here and I got the error 

    /usr/share/awesome/lib/awful/layout/init.lua:88 attempt to perform arithmetic on a table value (local 'i')

that @acyuta had reported. I was under the impression it was related to this issue, apparently not.

Either way, the Awful lib that got dropped in /usr/local/share/awesome/lib/awful/layout/init.lua does in fact spew its guts when presented with the current version of these themes.

In my /etc/xdg/awesome/rc.lua (see https://gist.github.com/chrisnorthcott/887d590e5accb2ad9dba) it has just the one parameter, a la

```lua
262     awful.key({ modkey,           }, "space", function () awful.layout.inc( 1) end),
263     awful.key({ modkey, "Shift"   }, "space", function () awful.layout.inc(-1) end),
```

which is odd... I'm guessing the other two are optional? Either way, it would appear that the argument order to awful.layout.inc is different to yours.

I think it might just be because I'm running the bleeding-edge awesomewm and these changes have not yet made their way into the stable/release branch. I dunno.

**Comment by copycat-killer** [comment]
Argh, [that's the exact point](https://github.com/copycat-killer/awesome-copycats#notes).

Unstable branch is not supported because... well, it's unstable.

**Comment by chrisnorthcott** [comment]
I didn't see that. Ah well, thanks for the clarification.

**Comment by robotanarchy** [comment]
@copycat-killer: thanks for fixing the bugs! but how is my initial report invalid? I can reproduce this, and it is only fixed when using your latest version. I am not using awesome from git, but the latest stable from the Arch Linux repositories.

**Comment by copycat-killer** [comment]
It is referred to the rest of the thread.

@github still doesn't allow to split issues.
