### ISSUE TITLE
After update to awesome v3.5.6 things are broken

### ISSUE THREAD

**Issue by zack6849** [copycat-killer/awesome-copycats#88]
Hello, i've updated awesome and lain and all of it's dependencies (in fact i even removed every file in ~/.config/awesome/ and re-downloaded them from git to ensure i had the newest versions, and i'm seeing some strangeness

For example, windows don't tile, they dont have proper margins, they cover awesome's bar at the top
I also receive this error:
`/home/zack6849/.config/awesome/lain/layout/uselesstile.lua:183: attempt to preform 'n%0'`
I've googled around and found people posting of similar issues in a couple places, mainly /g/ about it, however i don't see an official issue for it, and i'm not sure how to go about fixing it, so i figured filing an issue may help.

**Comment by copycat-killer** [comment]
Hi Zack,
the 'n%0' has been tackled in [lain #109](https://github.com/copycat-killer/lain/issues/109).

Are you sure you have the last commits? Remember you can use git for [a simple and fast installation](https://github.com/copycat-killer/awesome-copycats#installation).


Also, if are there other problems, can you please specify them?

**Comment by zack6849** [comment]
i am sure, as i said, i removed *all* files in ~/.config/awesome and then git cloned this repo, and copied the contents to ~/.config/awesome, is it possible the version you guys have linked in the git repo is behind somehow or something?

**Comment by copycat-killer** [comment]
You're right, I forgot to update git reference to lain last commit.

Thanks.

**Comment by zack6849** [comment]
Thanks for the fix, much appreciated! :+1:
