### ISSUE TITLE
Manually resizing windows

### ISSUE THREAD

**Issue by raj-kesavan** [copycat-killer/awesome-copycats#89]
Might be missing something - is it possible, with an awesome-copycats theme, to manually resize a window? By using the Mod4-Shift-H (etc.) keys - these work with default awesome but not with the theme. For example, if I want a window to take up the left half of the screen, how would I do that (other than making two windows in tiled, switch to floating view, and closing the second)?

**Comment by copycat-killer** [comment]
Are you referring to `awful.tag.incmwfact`? Yes, it's not present. You can add it with:

```lua
    awful.key({ modkey,           }, "l",     function () awful.tag.incmwfact( 0.05)    end),
    awful.key({ modkey,           }, "h",     function () awful.tag.incmwfact(-0.05)    end),
```

In any case, just copy stuff you need from the default config, if you can't find them in my themes.
