### ISSUE TITLE
Help for modifications 

### ISSUE THREAD

**Issue by Jokeezy** [copycat-killer/awesome-copycats#90]
Hello,

How can I delete the weather widget Blackburn theme? There are many files I do not know where withdraw

How can I change the Blackburn police?

And how I can change the color of the virtual desktops? (The name I do not want orange) ?

And remove the orange square of virtual desktops?

Thank you

**Comment by norpol** [comment]
> How can I delete the weather widget Blackburn theme?

I guess you need to remove the following lines:
https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L201-L207
https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L300-L301
https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L426

> How can I change the Blackburn police?

What?

> And how I can change the color of the virtual desktops? (The name I do not want orange) ?

Don't know what you mean, maybe: https://github.com/copycat-killer/awesome-copycats/blob/master/themes/blackburn/theme.lua#L17

**Comment by copycat-killer** [comment]
@norpol Thanks for your time.

@Jokeezy I recommend you to start from the basics.

https://awesome.naquadah.org/wiki/My_first_awesome
https://awesome.naquadah.org/wiki/Main_Page

Takes some time, but it's worthy.

I'll leave this issue open in order to help you achieve the customization you want.

**Comment by Jokeezy** [comment]
Thank'snorpol & @ copycat-Killet for answers

So if I want to withdraw the weather widget I just remove these lines:

https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L201-L207
https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L300-L301
https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L426

Nothing in the other files? There's so much I am lost.

How can I change the font of Blackburn theme?

The weather is not my area, how it is possible to keep it?

Here is a screen from the top bar, I would change the color is orange, and the orange icons change, how can I do?

http://i1.someimage.com/FJnGBNF.png

Thank's

**Comment by loudcry** [comment]
@Jokeezy 
>So if I want to withdraw the weather widget I just remove these lines

Exactly.
>How can I change the font of Blackburn theme?

Just edit `theme.font` and `theme.taglist_font` [lines](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/blackburn/theme.lua#L14-L15) in `themes/blackburn/theme.lua`

>The weather is not my area, how it is possible to keep it?

Read [wiki page](https://github.com/copycat-killer/lain/wiki/yawn). Copy `id` of your city from Yahoo Weather and replace [`123456`](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn#L202) with it.

>I would change the color of text

Change `fg` variables if you want another text color.
>and change icons orange

Did you mean color of the name of current tag ( virtual desktop ) or [`square_sel`](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/blackburn/icons/square_sel.png)? If first then edit `fg_taglist_focused`. If second then edit the image.

**Comment by Jokeezy** [comment]
@loudcry thank's for answer,

If I understand, if I dwell by exmeple in a village called "Verniolles" or "Pamiers" I pats on google:

Yahoo Pamiers (first link):
or
Yahoo Meteo Verniolles (first link):

And I take the number at the end of the link?

So thank you to remove a widget you go to rc.lua but not theme.lua? Finally there are no other lines in other files to remove?

Thank you I begin to understand, I spoke of the two I wanted to change the color of the two

Then let me know how I can add layouts on a theme?
because i love the high bar of theme "multicolor" and I would layouts theme "blackburn", so I thought maybe transfer widgets from the bar to the other theme or add the layouts I do not know how it's done

I tried to change the Intermediate Dialogue taglist got an error ^^

For the wallpaper, if I change wall.png, is what to a particular resolution? Or whatever the screen resolution will be supported automatically? Because I think that's how you change the wallpaper?

How can I add pipe (|) with a color to separate the widgets?

How can I change the color of widgets?

Is it possible to add a button to turn off power switch off and restart the computer, etc ...?

How can I change the icon next to dropbox widgets?

Is it possible to have an icon to the status of the next vpn widgets?

@ copycat killer is that you would have a link with white icons?

Thank you for your time I'll take a look at the wiki see if I can succeed, thank you for everything!

**Comment by copycat-killer** [comment]
Custom widgets like "number of updates" can be achieved with [abase](https://github.com/copycat-killer/lain/wiki/abase) or [base](https://github.com/copycat-killer/lain/wiki/base).

For the rest, the answer is "yes"/"read the wikis"/"practice a bit" to all.

**Comment by Jokeezy** [comment]
Thank you, I can change colors by changing the theme theme.lua but to retrieve the layouts of theme "blackburn" to put on "multicolor " it's hard

**Comment by copycat-killer** [comment]
@Jokeezy How's going?

**Comment by copycat-killer** [comment]
You had enough support, and since you seem to don't care anymore, I don't want a thread open for nothing.

Next time, use this function *only* for real issues.
