### ISSUE TITLE
I can't open terminal

### ISSUE THREAD

**Issue by liu0fanyi** [copycat-killer/awesome-copycats#91]
As title...
Thanks.

**Comment by copycat-killer** [comment]
Do you have `rxvt-unicode` or `xterm`? 

Otherwise just set your favourite terminal emulator.

**Comment by liu0fanyi** [comment]
I have xterm, it was work under awesome, after use copycats, I cant open terminal with Mod4+Enter....
Thanks!

**Comment by copycat-killer** [comment]
Please, don't raise issues for things you can "resolve" by yourself.
