### ISSUE TITLE
lain.widgets.yawn has been removed

### ISSUE THREAD

**Issue by xxinfinityxx** [copycat-killer/awesome-copycats#92]
Hi there, 

pretty much all the themes have a reference to the yawn widget which has been removed in favor of a new weather widget in https://github.com/copycat-killer/lain/commit/8c5b64675dfbf196871ee31cf22920627019bd84 as explained in issue https://github.com/copycat-killer/lain/issues/105

Right now, all the themes are failing to initialize because of this.

**Comment by copycat-killer** [comment]
I think I have updated everything properly.

Just pull latest commit.

Check [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.multicolor#L134-143) for an example of the new widget.

Let me know when you get everything working back again, or feel free to ask anything else.

**Comment by paescuj** [comment]
Some themes still has a reference to the old weather widget, like [rc.lua.holo, line 288](../blob/master/rc.lua.holo#L288). Therefore these themes are failing to initialize...

I would like to thank you for the great work on this way :)

**Comment by copycat-killer** [comment]
Gosh, I forgot how many configs used it.

Updated now. Thanks.
