### ISSUE TITLE
Multiple wallpapers 

### ISSUE THREAD

**Issue by dummys** [copycat-killer/awesome-copycats#93]
Hi, 

I'm trying to set multiple wallpapers with the theme-wallpaper_cmd but it's not working.
Here the command line I tried:

theme.wallpaper_cmd = feh --bg-scale /home/user/.config/awesome/themes/steamburn/wall1.png --bg-scale /home/user/.config/awesome/themes/steamburn/wall2.png

theme.wallpaper_cmd = { feh --bg-scale /home/user/.config/awesome/themes/steamburn/wall1.png --bg-scale /home/user/.config/awesome/themes/steamburn/wall2.png }

wallpaper_cmd = { feh --bg-scale /home/user/.config/awesome/themes/steamburn/wall1.png --bg-scale /home/user/.config/awesome/themes/steamburn/wall2.png }
etc...

did you have an idea ?
Thanks

**Comment by norpol** [comment]
Hi.
This won't work since you are just overwriting one command by another.
Do you want to cycle through multiple images randomly? This  [here](https://awesome.naquadah.org/wiki/Cycling_Random_Wallpaper_Or_Xscreensaver) might give you a better understanding and [this solution](https://bbs.archlinux.org/viewtopic.php?pid=1243915#p1243915) looks more easy to use. Or did I understand you wrong, and you've got plenty of displays and you want to set for every display a different wallpaper?

**Comment by dummys** [comment]
Yes the later one.  Ive done a very ugly hack in the rc.lua but I'm not
happy with it. If you have a cleaner solution I'm open.

**Comment by copycat-killer** [comment]
This is not related to my repository, however, I'll try to help you.

One simple solution would be to set your wallpapers path in a table.

In your `theme.lua`, rewrite your `theme.wallpaper` like this:

```lua
theme.wallpaper = { "path/to/first/wallie", "path/to/second/wallie", "and/so/on" }
```

That is, transform it into a table of paths. Then, in your `rc.lua`, replace your wallpaper section with this one:

```lua
-- {{{ Wallpaper
if beautiful.wallpaper then
    for s = 1, screen.count() do
        gears.wallpaper.maximized(beautiful.wallpaper[s], s, true)
    end
end
-- }}}
```

the only modification is that now `beautiful.wallpaper` can be iterated with index `s`.

This should work.

**Comment by norpol** [comment]
@copycat-killer Thank you!

**Comment by dummys** [comment]
Yes,  the problem is I, want the first maximazed and the other one
centralized. So perhaps its better to fo a runonce with a feh - -etc ?

**Comment by copycat-killer** [comment]
@dummys Then, assuming you set `theme.wallpaper` like above, set your wallpaper section like this:

```lua
-- {{{ Wallpaper
if beautiful.wallpaper then
    gears.wallpaper.maximized(beautiful.wallpaper[1], 1, true)
    for s = 2, screen.count() do
        gears.wallpaper.centered(beautiful.wallpaper[s], s)
    end
end
-- }}}
```

This way your first monitor will have a maximized wallpaper, while every other next will have a centered one.

You can avoid using external tools like `feh`, since it can be done via Awesome. Read [its API](https://awesome.naquadah.org/doc/api/modules/gears.wallpaper.html) for the rest.

**Comment by dummys** [comment]
Thanks a lot for your solution.

**Comment by copycat-killer** [comment]
@dummys If you want to use `feh`, it's trivial to modify your wallpaper section like this:

```lua
-- {{{ Wallpaper
if beautiful.wallpaper then
    awful.util.spawn_with_shell("feh --bg-scale " .. beautiful.wallpaper[1])
    for s = 2, screen.count() do
        gears.wallpaper.centered(beautiful.wallpaper[s], s)
    end
end
-- }}}
```

**Comment by dummys** [comment]
@copycat-killer yes but if I can not use third parties utilities it's better. But I really don't know why my image is cropped at the left with the gears.wallpapers.maximized.

**Comment by copycat-killer** [comment]
Did you read the [API](https://awesome.naquadah.org/doc/api/modules/gears.wallpaper.html#maximized)? Try setting that `true` to `false`, or entering an `offset` table.

**Comment by dummys** [comment]
Yes I tried the true or false, but not the offset, will try.. thanks

**Comment by copycat-killer** [comment]
You can set it like this:

```lua
gears.wallpaper.maximized(beautiful.wallpaper[1], 1, true, {x = 10, y = 10})
```

Other than this, I'm afraid I can't help you further. You may want to ask awesome devel.

**Comment by cr1ogen** [comment]
Maybe can help you 
 ```
awesome.naquadah.org/wiki/Cycling_Random_Wallpaper_Or_Xscreensaver
 ```

**Comment by dummys** [comment]
That's it copycat-killer. With the x,y it's finally fine working. Thanks for your help and for your insane work on awesome.
