### ISSUE TITLE
Question about the Net widget.

### ISSUE THREAD

**Issue by Incognito4nonymous** [copycat-killer/awesome-copycats#94]
Hello again, I have a permission problem with the net widget and I don't want to use sudo, what should I do?

I tried with `su -c` but it doesn't work.

**Comment by copycat-killer** [comment]
This is what comes up in my mind:

1. try to *slack your ware* on these unharmful situations; :grinning:
2. try modifying `net.lua` in order to point to local symbolic `/sys/class/net` links instead.

**Comment by copycat-killer** [comment]
Any update on this?

If not, tell me how can I help.

**Comment by Incognito4nonymous** [comment]
Actually I have done nothing for now :)

But I will probably soon need the widget, but there is something I don't understand, how can I run the widget without Sudo ?

**Comment by copycat-killer** [comment]
>But I will probably soon need the widget, but there is something I don't understand, how can I run the widget without Sudo ?

This is related to your system, not the widget itself. Even if I have no ideas, [I already tried to answer you](https://github.com/copycat-killer/awesome-copycats/issues/94#issuecomment-129426480).

>Oh, and why when I click on the wiget a window says : "unknown command "-g" " ?

I suppose you're using [Powerarrow Darker](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.powerarrow-darker#L73). This is **again** a parser problem, just like [here](https://github.com/copycat-killer/lain/issues/112). You have to check if your `SHELL` environment variable, and your `terminal` definition in `rc.lua`. Or you can just remove the `-g arg` parameter.

**Comment by Incognito4nonymous** [comment]
Problem solved, here is the workaround : 
On line 30.
local ws = helpers.read_pipe("ip link show[bla bla bla]
Just add 
local ws = helpers.read_pipe("usr/sbin/ip link show[bla bla bla]
Hope it helps someone.
