### ISSUE TITLE
amixer toggle does not unmute all muted channels

### ISSUE THREAD

**Issue by awayanyway** [copycat-killer/awesome-copycats#95]
The key binding for mute/unmute in Alsa volume control does mute both Master and PCM, but unmute only Master. Solutions that work for me: 
- `amixer -D pulse set %s toggle`
- `amixer set %s toggle && amixer set PCM unmute`

Cheers,

Pi

**Comment by awayanyway** [comment]
actually,  I changed the rc.lua to use  the args of the lain alsa widget:
volumewidget = lain.widgets.alsa({
......
 cmd = "amixer -D pulse"
}
and for all  of the volume key bindings (as in lain alsa.lua):
("%s set %s ...... ", volumewidget.cmd, volumewidget.channel))
If you think this is useful, I could fork/request

Best,

Pi

**Comment by copycat-killer** [comment]
I think this is a use case. I'll put a link in the [wiki](https://github.com/copycat-killer/lain/wiki/alsa).

**Comment by zobi8225** [comment]
ok . thx
