### ISSUE TITLE
What are these layouts ?

### ISSUE THREAD

**Issue by Jok3r0** [copycat-killer/awesome-copycats#96]
Hello,

Is not someone layouts which are used in these screens?

Thank you

1 : http://img00.deviantart.net/1ad3/i/2013/235/a/3/_arch___awesomewm__home_desktop_august_2013_by_transienceband-d6jcj72.png

2 : http://img10.deviantart.net/b697/i/2013/207/8/5/arch_linux_and_awesome_wm__july_27th_2013__by_transienceband-d6fd5z0.png

**Comment by copycat-killer** [comment]
Just floating windows manually arranged.

**Comment by Jok3r0** [comment]
Thank you :)

**Comment by copycat-killer** [comment]
Yes, in both.
